module.exports=function({fs,path,D,ROOT,R,esc:E,shell,write,card,index}){
const data=require('./content/evolution.cjs'),{academy,micro,lab,taxonomy,sources}=data;
const grid=items=>`<div class="hub-grid">${items.map(([title,url,desc])=>`<a class="hub-card" href="${E(url)}"><h2>${E(title)} →</h2><p>${E(desc||'')}</p></a>`).join('')}</div>`;
const page=(route,title,desc,body,active='formation')=>{write(route,shell(title,active,`<div class="eyebrow">SCOLAR·IA · Pratique enseignante</div><h1>${E(title)}</h1><p class="intro">${E(desc)}</p>${body}`));index.push({title,desc,route:'/'+route+'/',text:body.replace(/<[^>]*>/g,' '),type:route.startsWith('academy')||route==='micro-formations'?'formation':route.startsWith('lab')?'atelier':route.startsWith('modeles')?'modele':'guide'})};
const opts=rows=>rows.map(v=>`<option>${E(v)}</option>`).join('');
const field=(label,name,values)=>`<label>${E(label)}${values?`<select name="${name}">${opts(values)}</select>`:`<input name="${name}" required maxlength="240">`}</label>`;
const local='<p class="scope-note">Traitement dans votre navigateur. Aucun contenu n’est envoyé à une IA. Utilisez des exemples fictifs ; l’export reste sous votre contrôle.</p>';
page('academy','SCOLARIA Academy','Dix parcours par besoin, de la découverte à la conception. Choisissez votre objectif ; vos cinq niveaux existants restent accessibles.',`<div class="action-row"><a class="btn secondary" href="/formation/">Retrouver mes 5 niveaux</a><a class="btn secondary" href="/micro-formations/">J’ai 3, 5 ou 10 minutes</a><a href="/diagnostic/">Faire le diagnostic</a></div><p><strong id="academy-count">0 parcours terminés sur 10</strong></p><progress id="academy-progress" value="0" max="10" aria-label="Progression Academy"></progress>${grid(academy.map((a,i)=>[(i+1)+'. '+a.title,'/academy/'+a.id+'/',a.minutes+' min · '+a.difficulty+' · '+a.objective]))}<section class="panel"><h2>Un repère, pas une certification</h2><p>Ces parcours originaux s’appuient sur les dimensions et la progression du cadre UNESCO : acquérir, approfondir et créer. Ils ne reproduisent pas une formation officielle et ne délivrent pas de certification.</p><a href="${sources.unesco}" target="_blank" rel="noopener">Cadre UNESCO pour les enseignants ↗</a><p class="scope-note">Source consultée le 15 septembre 2026.</p></section>`);
for(const a of academy)page('academy/'+a.id,a.title,a.objective,`<p class="badge">${E(a.difficulty)} · ${E(a.stage)} · ${a.minutes} min</p><article class="article"><h2>Votre production finale</h2><p>${E(a.production)}</p><ol class="steps"><li><strong>1. Comprendre · environ 1/3 du temps</strong><a href="${a.learn}">Lire les repères et exemples</a>. Relever une idée utile et une limite.</li><li><strong>2. Mettre en pratique · environ 1/2 du temps</strong><a href="${a.practice}">Ouvrir l’atelier associé</a>. ${E(a.production)}</li><li><strong>3. Vérifier · temps restant</strong>Comparer le résultat au programme et aux acquis de votre classe. Préparer une variante sans connexion. Documenter ce qui reste à confirmer.</li></ol><form class="quiz-form" data-academy="${a.id}"><fieldset><legend>${E(a.question)}</legend>${a.answers.map((s,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i}" required>${E(s)}</label>`).join('')}</fieldset><label class="answer-option"><input type="checkbox" name="practice" required>J’ai produit et relu la réalisation demandée.</label><button class="btn">Vérifier et enregistrer ma progression</button><div class="result-panel" data-academy-result role="status" hidden></div></form><p class="scope-note">La réalisation est déclarée par vous-même ; le portail ne l’évalue pas automatiquement.</p><a href="/academy/">← Tous les parcours</a></article>`);
page('micro-formations','Apprendre en quelques minutes','Neuf gestes précis à essayer immédiatement, puis à vérifier.',grid(micro.map(m=>[m.title,'/ressources/micro-'+m.id+'/',m.minutes+' min · '+m.objective])));
page('lab','SCOLARIA Lab','Six ateliers pour préparer, structurer et contrôler votre travail.',local+grid(lab.map(l=>[l.title,'/lab/'+l.id+'/',l.desc]))+'<section class="panel"><h2>Comment fonctionnent ces ateliers ?</h2><p>Ils assemblent des modèles et des listes de contrôle. Le quiz et l’adaptation préparent des prompts à copier dans l’outil de votre choix ; ils ne produisent pas de réponses validées par une IA. La grille et le déroulement sont des trames modifiables. L’analyseur ne détecte pas automatiquement les erreurs.</p></section>','prompts');
for(const l of lab){const input=l.id==='analyser'?'Réponse fictive à examiner':l.id==='ameliorer-prompt'?'Votre demande initiale':l.id==='quiz'?'Extrait de cours autorisé':l.id==='adapter'?'Consigne ou ressource à adapter':'Contexte et contraintes (facultatif)';page('lab/'+l.id,l.title,l.desc,local+`<form class="panel" id="lab-form" data-lab="${l.id}"><div class="form-grid">${l.id==='analyser'?'':field('Discipline','discipline',taxonomy.subjects)+field('Niveau scolaire','level',taxonomy.levels)+field('Objectif observable','objective')}<label class="wide">${input}<textarea name="text" rows="6" maxlength="12000" ${['analyser','ameliorer-prompt','quiz','adapter'].includes(l.id)?'required':''}></textarea></label>${l.id==='activite'?'<label>Durée totale (minutes)<input type="number" name="minutes" min="15" max="120" value="45" required></label>':''}${l.id==='quiz'?'<label>Nombre de questions<input type="number" name="questions" min="3" max="15" value="5" required></label>':''}</div><button class="btn">${l.id==='analyser'?'Préparer mon journal de vérification':'Construire mon modèle'}</button></form><section id="lab-output" class="panel" hidden><h2>Votre brouillon, à relire</h2><div id="lab-analysis"></div><label>Texte modifiable<textarea id="lab-text" rows="16" maxlength="40000"></textarea></label><div class="actions-wrap"><button class="btn" data-lab-action="copy">Copier</button><button class="btn secondary" data-lab-action="save">Sauvegarder</button><button class="btn secondary" data-lab-action="export">Télécharger en texte</button><button class="btn secondary" data-lab-action="edit">Modifier</button></div><p id="lab-status" role="status"></p></section><p><a href="/lab/">← Tous les ateliers</a> · <a href="/generateur/">Prompt Builder complet</a></p>`,'prompts');}
page('maintenance','Suivi des vérifications','Une vue publique pour comprendre ce qui a été consulté et ce qui demande une revue. Une date n’est jamais une garantie globale.',`<div class="panel"><label>État à afficher<select id="maintenance-state"><option value="review">À vérifier ou revue arrivée à échéance</option><option value="all">Toutes les fiches</option><option value="documented">Avec une consultation documentée</option></select></label><p id="maintenance-count" role="status"></p><div class="table-wrap"><table><thead><tr><th>Ressource</th><th>Consultation</th><th>Prochaine revue</th><th>Portée</th></tr></thead><tbody id="maintenance-results"></tbody></table></div></div><p>Les échéances à 90 jours sont une règle de maintenance du portail. Une vérification de prix ou d’accès ne vaut pas validation juridique, pédagogique ou de sécurité.</p>`,'sources');
page('donnees-maroc','Données des élèves : décider avant de transmettre','Un parcours pratique pour les enseignants au Maroc, à examiner avec le responsable du traitement de leur établissement.',`<article class="article"><h2>1. Le besoin pédagogique</h2><p>Pouvez-vous travailler avec une consigne générale ou un exemple fictif ? Commencez par cette solution. Un nom retiré d’un fichier ne suffit pas si une voix, une photo, une écriture ou un récit permet encore d’identifier une personne.</p><h2>2. Repère juridique</h2><p><span class="badge">Obligation juridique à examiner</span> La loi 09-08 encadre les traitements de données personnelles au Maroc. Les transferts à l’étranger relèvent notamment de ses articles 43 et 44. La CNDP explique les situations prévues et les démarches ; la présence d’un hébergement cloud étranger demande un examen du traitement et du transfert.</p><p><a href="${sources.cndp}" target="_blank" rel="noopener">CNDP : transfert de données à l’étranger ↗</a> · <a href="${sources.loi}" target="_blank" rel="noopener">CNDP : présentation de la loi 09-08 ↗</a></p><h2>3. Décision de l’établissement</h2><p><span class="badge">Recommandation</span> Faire préciser la finalité, les catégories de données, les destinataires, la durée de conservation, les mesures de sécurité, les droits des personnes et les formalités applicables. Ne pas supposer qu’un consentement ou un abonnement « éducation » règle toutes ces questions.</p><h2>4. Mesures immédiates en classe</h2><p><span class="badge">Bonne pratique</span> Utiliser un support fictif commun, ne pas charger de liste de notes ou de comptes rendus de santé, préparer une alternative sans compte élève et contrôler les productions avant diffusion.</p><h2>Checklist de décision</h2><ul><li>Quel apprentissage est visé ?</li><li>Le service reçoit-il du texte, des fichiers, des photos ou de la voix ?</li><li>Qui pourrait reconnaître la personne ?</li><li>Quel contrat et quels paramètres correspondent à l’offre réellement utilisée ?</li><li>Quels pays, destinataires, durées et usages ultérieurs sont documentés ?</li><li>Qui valide la décision et conserve sa justification ?</li></ul><p class="scope-note">Sources officielles consultées le 15 septembre 2026. Ce guide organise les questions ; il ne délivre aucune autorisation de traitement.</p></article>`,'ethique');
const templates=[
['charte-etablissement','Charte d’établissement','Objectifs pédagogiques autorisés : …\nResponsable désigné et interlocuteur données : …\nServices et offres examinés : …\nDonnées exclues et alternatives fictives : …\nRègles d’accès équitable : …\nValidation humaine avant diffusion et notation : …\nInformation des élèves et des familles : …\nProcédure de signalement et de révision : …\nDate de validation interne et prochaine revue : …'],
['charte-enseignant','Engagements de l’enseignant','Je pars d’un objectif d’apprentissage précis.\nJe vérifie les contenus, les sources et les droits.\nJe prépare des exemples fictifs et protège les données.\nJe rends explicites les aides autorisées.\nJe conserve une décision humaine sur l’évaluation.\nJe prévois une alternative sans compte ni abonnement.'],
['charte-eleve','Engagements de l’élève','Je lis la consigne et demande quelles aides sont autorisées.\nJe ne communique pas de données sur moi ou mes camarades à un service IA.\nJe vérifie les informations et consulte les documents cités.\nJe déclare mon utilisation de l’IA.\nJe peux expliquer ce que je rends avec mes propres mots.\nSi une réponse m’inquiète ou me trompe, j’en parle à mon enseignant.'],
['regles-classe','Règles pour une activité','Activité et objectif : …\nIA interdite / autorisée sous conditions / recommandée : …\nPourquoi ce choix : …\nAides permises : …\nTravail à réaliser seul : …\nDonnées interdites dans les prompts : …\nTrace d’usage demandée : …\nAlternative sans IA : …'],
['journal-travail','Journal du travail et des aides','Date et étape : …\nCe que j’ai essayé seul : …\nOutil ou personne consultée : …\nQuestion posée sans donnée personnelle : …\nCe que j’ai retenu et pourquoi : …\nCe que j’ai rejeté ou corrigé : …\nSource ou calcul de vérification : …\nProchaine étape : …'],
['justification','Fiche de justification','Ma réponse finale : …\nMon raisonnement en trois étapes : …\nLa preuve la plus importante : …\nUne erreur corrigée : …\nL’aide utilisée et sa limite : …\nUne variante que je peux résoudre sans aide : …'],
['autoevaluation','Auto-évaluation de la démarche','Je peux expliquer la notion : pas encore / avec aide / seul.\nJe peux justifier une décision : pas encore / avec aide / seul.\nJe sais quelle information reste incertaine : …\nJ’ai déclaré les aides : …\nMa prochaine amélioration précise : …']
];
for(const [id,title,text]of templates){fs.mkdirSync(path.join(D,'modeles'),{recursive:true});fs.writeFileSync(path.join(D,'modeles',id+'.txt'),'SCOLAR·IA — '+title+'\nModèle pédagogique à adapter et valider par l’établissement.\n\n'+text+'\n');page('modeles/'+id,title,'Un modèle original à adapter, imprimer ou télécharger.',`<article class="article"><pre class="template-text">${E(text)}</pre><div class="actions-wrap"><a class="btn" href="/modeles/${id}.txt" download>Télécharger le modèle texte</a><button class="btn secondary" data-print>Imprimer</button></div><p class="scope-note">Ce modèle ne remplace pas les formalités applicables et ne constitue pas une autorisation de traitement de données.</p></article>`,'evaluation');}
page('modeles','Chartes et traces de travail','Sept modèles modifiables, en complément des déclarations et PDF déjà disponibles.',grid(templates.map(([id,title])=>[title,'/modeles/'+id+'/','Téléchargement texte et impression A4.']))+'<p><a href="/declarations/">Déclarations d’usage de l’IA existantes</a> · <a href="/telechargements/">Tous les téléchargements</a></p>','evaluation');
function append(route,html){const f=path.join(D,route,'index.html');fs.writeFileSync(f,fs.readFileSync(f,'utf8').replace('</main>',html+'</main>'));}
for(const route of ['formation','enseigner','explorer'])append(route,'<section class="section"><h2>Aller plus loin avec SCOLARIA</h2>'+grid([['Academy','/academy/','10 parcours par objectif'],['Micro-formations','/micro-formations/','3, 5 ou 10 minutes'],['Lab','/lab/','6 ateliers pratiques']])+'</section>');
for(const route of ['evaluation','telechargements','charte'])append(route,'<section class="panel"><h2>Des modèles prêts à adapter</h2><a href="/modeles/">Chartes, journal de travail, justification et auto-évaluation →</a></section>');
append('ethique','<section class="panel"><h2>Avant de transmettre des données</h2><a href="/donnees-maroc/">Parcours de décision dans le contexte marocain →</a></section>');
append('observatoire','<section class="panel"><h2>Dernières revues documentaires</h2><p>15 septembre 2026 · Conditions d’accès et documentation de cinq outils existants. Revue ciblée, sans déclaration de validation globale.</p>'+grid(R.filter(r=>r.reviewEvidence).map(r=>[r.title,'/ressources/'+r.id+'/',r.reviewEvidence.scope.join(' · ')]))+'<a href="/maintenance/">Suivre les fiches à vérifier →</a></section>');
append('espace','<section class="panel"><h2>Des pistes pour votre profil</h2><p>Suggestion par correspondance de discipline et de besoin, sans classement de qualité des outils.</p><div id="profile-recommendations"></div><a href="/academy/">Ma progression Academy →</a></section>');
for(const r of R){if(r.type==='outil'){const similar=R.filter(x=>x.type==='outil'&&x.id!==r.id&&x.useCases.some(u=>r.useCases.includes(u))).slice(0,3);const prompts=R.filter(x=>x.type==='prompt'&&x.useCases.some(u=>r.useCases.includes(u))).slice(0,2);append('ressources/'+r.id,`<section class="panel"><h2>Repères structurés</h2><p class="badge">${E(r.toolKind)}</p><dl class="resource-metadata"><dt>Compte</dt><dd>${E(r.accountAccess)}</dd><dt>Usage par les élèves</dt><dd>${E(r.studentAccess)}</dd><dt>Âge minimal</dt><dd>À vérifier</dd><dt>Français / arabe</dt><dd>${E(r.documentation.french)} / ${E(r.documentation.arabic)}</dd><dt>Sans connexion</dt><dd>${E(r.offline)}</dd><dt>Confidentialité</dt><dd>À vérifier ; aucune qualification automatique de sécurité.</dd><dt>Données envoyées</dt><dd>Examiner les textes, fichiers et métadonnées transmis selon la fonction choisie.</dd><dt>Politique de confidentialité</dt><dd>À consulter pour l’offre utilisée sur le site officiel.</dd><dt>Données réelles d’élèves</dt><dd>Aucune autorisation déduite de cette fiche.</dd><dt>Consultation documentaire</dt><dd>${E(r.verifiedAt||'À vérifier')}</dd><dt>Prochaine revue</dt><dd>${E(r.reviewAfter||'À planifier')}</dd></dl>${r.reviewEvidence?`<h3>Ce qui a effectivement été consulté</h3><p>${E(r.reviewEvidence.note)}</p><a href="${E(r.reviewEvidence.source)}" target="_blank" rel="noopener">Document officiel consulté ↗</a>`:''}<h3>Des usages à comparer</h3>${grid(similar.map(s=>[s.title,'/ressources/'+s.id+'/',s.desc]))}<h3>Prompts associés au besoin</h3>${prompts.map(p=>`<p><a href="/ressources/${p.id}/">${E(p.title)}</a></p>`).join('')||'<p>À compléter après examen pédagogique.</p>'}</section>`);}}
// Filtres canoniques ajoutés aux formulaires existants ; valeurs historiques conservées.
const extra=[['accountAccess','Compte',taxonomy.accountAccess],['studentAccess','Usage élève',taxonomy.studentAccess],['toolKind','Type d’outil',taxonomy.toolKinds],['useCase','Besoin pédagogique',taxonomy.useCases.map(u=>u.label)],['privacyLevel','Confidentialité',['À vérifier']],['learningTime','Temps disponible',['3 minutes','5 minutes','10 minutes','Moins de 60 min','60 min et plus']],['provider','Organisme / éditeur',[...new Set(R.map(r=>r.provider).filter(Boolean))].sort()],['verifiedYear','Année de consultation documentée',[...new Set(R.map(r=>r.verifiedAt?.slice(0,4)).filter(Boolean))].sort()]];
for(const route of ['bibliotheque','outils','prompts','tutoriels','scenarios','sources','favoris']){const f=path.join(D,route,'index.html');let h=fs.readFileSync(f,'utf8');h=h.replace('</details><div class="results-bar">',`<div class="filters">${extra.map(([key,label,values])=>`<label>${label}<select name="${key}" data-filter="${key}"><option value="">Tous</option>${opts(values)}</select></label>`).join('')}</div></details><div class="results-bar">`);h=h.replace('<option value="Freemium">','<option value="Gratuit sous conditions">Gratuit sous conditions</option><option value="Freemium">');fs.writeFileSync(f,h);}
let g=fs.readFileSync(path.join(D,'generateur/index.html'),'utf8');g=g.replace('Un prompt construit pour votre classe','Prompt Builder SCOLARIA');g=g.replace('<button class="btn" data-generated="copy">','<button class="btn secondary" type="button" data-prompt-mode="short">Version courte</button><button class="btn secondary" type="button" data-prompt-mode="advanced">Version avancée</button><button class="btn secondary" type="button" data-prompt-mode="edit">Modifier</button><button class="btn secondary" type="button" data-prompt-mode="regenerate">Régénérer</button><button class="btn" data-generated="copy">');fs.writeFileSync(path.join(D,'generateur/index.html'),g);
let space=fs.readFileSync(path.join(D,'espace/index.html'),'utf8');space=space.replace('<label><input type="checkbox" name="lowBandwidth">',field('Langue de travail','workingLanguage',['Français','Arabe','Anglais'])+field('Besoin prioritaire','interest',taxonomy.useCases.map(u=>u.label))+'<label><input type="checkbox" name="lowBandwidth">');fs.writeFileSync(path.join(D,'espace/index.html'),space);
let privacy=fs.readFileSync(path.join(D,'confidentialite/index.html'),'utf8').replace('Une version publiée utiliserait les mécanismes d’accès et journaux techniques de son hébergeur.','La version publiée est hébergée par Vercel, qui traite les requêtes et journaux techniques nécessaires à l’hébergement.');fs.writeFileSync(path.join(D,'confidentialite/index.html'),privacy);
const {locales,arabicShell}=require('./content/i18n.cjs'),ar=locales.ar;
const arRoutes=['/generateur/','/lab/activite/','/outils/','/prompts/','/evaluation/','/enseigner-ia/','/comprendre/','/donnees-maroc/','/academy/','/observatoire/'];
write('ar',arabicShell(shell(ar.homeTitle,'accueil',`<section class="scolar-hero"><div class="eyebrow">التعليم الثانوي الإعدادي والتأهيلي · المغرب</div><h1>${ar.homeTitle}</h1><p class="intro">${ar.intro}</p><form class="searchbox" action="/bibliotheque/"><input name="q" aria-label="البحث في البوابة" placeholder="${ar.search}"><button class="btn">بحث</button></form><p class="lang-note">${ar.note}</p></section><h2>${ar.search}</h2><div class="task-grid">${ar.tasks.map((t,i)=>`<a class="task-link" href="${arRoutes[i]}">${t}<small>المورد بالفرنسية</small></a>`).join('')}</div><section class="panel"><h2>ثلاث خطوات قبل الاستعمال</h2><ol><li>حدد ما ينبغي أن يتعلمه المتعلم ويستطيع شرحه بنفسه.</li><li>ابدأ بمثال خيالي دون أسماء أو صور أو معلومات تسمح بالتعرف على الأشخاص.</li><li>تحقق من المعلومات والمصادر ومن ملاءمة النشاط لمقرر الفصل.</li></ol><p><a href="/ar/demarche/">دليل البداية بالعربية ←</a></p></section>`)));
// Keep the existing Arabic guide if its route differs; never remove a prior page.
page('ar/demarche','دليل البداية','خطوات عملية لبداية مسؤولة.', '<article class="article"><h2>اختر مهمة محدودة</h2><p>أعد صياغة تعليمة قصيرة تعرف معناها. قارن الناتج بالأصل ولا تقبل تغيير الهدف.</p><h2>اكتب سياقًا كافيًا</h2><p>حدد المادة والمستوى والمدة والشكل المطلوب. لا تكتب أي بيانات عن متعلم حقيقي.</p><h2>تحقق ثم عدّل</h2><p>راجع الحقائق والحسابات والمراجع، واطلب من المتعلم تفسير اختياره بنفسه.</p><p><a href="/ar/">العودة إلى الرئيسية</a></p></article>');
const arGuide=path.join(D,'ar/demarche/index.html');fs.writeFileSync(arGuide,arabicShell(fs.readFileSync(arGuide,'utf8')));
fs.writeFileSync(path.join(D,'locales.json'),JSON.stringify(locales,null,2));
fs.writeFileSync(path.join(D,'evolution-data.json'),JSON.stringify({academy,micro,lab,taxonomy}));
fs.writeFileSync(path.join(D,'taxonomy.json'),JSON.stringify(taxonomy,null,2));
fs.writeFileSync(path.join(D,'catalogue-v2.json'),JSON.stringify(R.map(r=>({id:r.id,type:r.type,title:r.title,slug:r.slug,description:r.desc,subjects:r.subjects,levels:r.levels,languages:r.languages,useCases:r.useCases,skills:r.skills,provider:r.provider,url:r.link||null,pricing:r.cost,accountRequired:r.accountAccess==='Compte requis'?true:r.accountAccess==='Sans compte possible'?false:null,studentUse:r.studentAccess,ageMinimum:r.ageMinimum,privacyLevel:r.privacyLevel,studentDataAllowed:r.studentDataAllowed,officialSource:r.reviewEvidence?.source||r.link||null,verifiedAt:r.verifiedAt,editorialReviewedAt:r.editorialReviewedAt,reviewAfter:r.reviewAfter,status:r.lifecycleStatus,translations:r.translations})),null,2));
};
