// Contenu éditorial séparé de l'interface. Les fiches générées sont exportées en JSON.
const original=require('./source-originale.json');
const date='2026-09-15';
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const cats={general:'Assistants généralistes',research:'Recherche & documentation',prep:'Préparation de cours',eval:'Évaluation',visual:'Supports & présentations',image:'Images',video:'Vidéo & audio',interactive:'Collaboration en classe',language:'Langues & traduction',math:'Mathématiques & sciences',access:'Accessibilité',tutor:'IA avec les élèves',organize:'Productivité',detect:'Intégrité académique',seq:'Préparation de cours',diff:'Différenciation',comm:'Communication',gestion:'Gestion de classe',reme:'Remédiation',matiere:'Disciplines',prof:'Formation',write:'Feedback',integrity:'Intégrité académique',code:'Programmation',open:'Ressources éducatives ouvertes',ethique:'Cadre juridique & éthique'};
const toolDescriptions=[
'Assistant conversationnel pour préparer un plan de séance, reformuler une consigne et explorer des exemples. Les résultats demandent une validation pédagogique.',
'Assistant pour rédiger, analyser un texte et retravailler des documents. Utile pour confronter plusieurs versions d’une consigne.',
'Assistant de Google pour explorer une question et produire un premier brouillon. Les intégrations aux autres services dépendent du compte et de l’offre.',
'Assistant de Microsoft pour rédiger et organiser des idées. Distinguer le service conversationnel des fonctionnalités intégrées à Microsoft 365.',
'Service de recherche assistée proposant des réponses accompagnées de références. Ouvrir les sources pour contrôler ce qu’elles démontrent réellement.',
'Espace de travail Google autour de documents sélectionnés. Utile pour interroger un dossier documentaire et retrouver les passages cités ; la fidélité reste à vérifier.',
'Plateforme de préparation pédagogique proposant notamment plans de cours, rubriques et aide au feedback. Adapter les modèles au programme marocain.',
'Assistant pour enseignants disponible notamment comme extension de navigateur. Aide à transformer des documents en activités et à préparer des retours.',
'Plateforme de création de ressources pédagogiques. Fiche issue du catalogue initial ; fonctionnalités et conditions d’accès à revalider.',
'Plateforme éducative mentionnée dans le catalogue initial pour les cours et activités. Offre actuelle non confirmée lors de cette révision.',
'Plateforme de gestion et de correction d’évaluations. L’enseignant définit les critères et conserve la décision sur la note.',
'Wayground, anciennement Quizizz : plateforme d’activités et d’évaluations interactives, avec des fonctions de création assistée.',
'Assistant de rédaction pour retravailler la langue et la clarté. Utiliser ses suggestions comme support d’explication, sans remplacer la grille du professeur.',
'Outil de création de documents, présentations et supports visuels. L’offre Éducation dépend de l’éligibilité et de la vérification par Canva.',
'Outil de création de présentations à partir d’un plan. Relire le fond avant de choisir une mise en page et vérifier les options d’export de son offre.',
'Outil d’adaptation de ressources de lecture et d’activités. Vérifier que la simplification conserve l’objectif et les notions à enseigner.',
'Outil d’interactivité intégré à PowerPoint pour faire participer la classe. Tester la compatibilité et les fonctionnalités avec son installation.',
'Fonctions de création de médias dans Canva. Une illustration générée n’est pas un document historique ou scientifique authentique.',
'Création d’images avec des assistants conversationnels. Fiche conservée pour cet usage ; possibilités et quotas varient selon le service et le compte.',
'Outil de génération d’images, dont des compositions contenant du texte. Contrôler chaque légende et chaque élément visuel avant utilisation.',
'Éditeur vidéo proposant des fonctions assistées, notamment pour préparer des capsules. Relire les sous-titres et vérifier les droits des médias.',
'Fonction de synthèse audio de documents dans l’environnement NotebookLM. Écouter entièrement le résultat et fournir aussi une version textuelle.',
'Plateforme de quiz utilisable pour une vérification rapide de compréhension. Prévoir une modalité papier ou collective sans compte élève.',
'Outil de questions interactives, sondages et participation. Utile pour recueillir des hypothèses avant de les discuter en classe.',
'Plateforme de leçons interactives. Prévoir une alternative pour les élèves sans équipement et tester les conditions d’accès.',
'Service de traduction. Comparer la traduction au texte source et faire relire les termes disciplinaires par une personne compétente.',
'Assistant de reformulation. Les langues et fonctions disponibles sont à vérifier ; ne pas lui confier des échanges contenant des données d’élèves.',
'Application d’aide à la résolution mathématique. Faire expliquer et vérifier les étapes, puis proposer un exercice similaire sans assistance.',
'Moteur de calcul et de connaissances structuré. Utile pour contrôler une expression ou explorer une représentation ; expliciter les hypothèses.',
'Outil de reconnaissance de contenu mathématique vers des formats éditables. Vérifier signes, exposants, indices et mise en forme après conversion.',
'Service de lecture vocale. Tester la prononciation des termes du cours et l’utilité réelle du support avec l’élève.',
'LireCouleur et OpenDyslexic : aides à la mise en forme et à la lecture, complémentaires à l’IA. L’effet varie selon les lecteurs ; tester avant de généraliser.',
'Outils de lecture assistée de Microsoft. Vérifier leur disponibilité dans l’application utilisée et régler l’affichage selon les préférences du lecteur.',
'Assistant et tuteur IA de Khan Academy. Vérifier les pays, langues, âges et modalités d’accès avant de prévoir une utilisation par les élèves.',
'Fonctions d’assistance dans Notion pour structurer et retravailler des notes. À réserver à des contenus professionnels sans données personnelles d’élèves.',
'Service d’estimation de l’origine IA d’un texte. Ses résultats ne constituent pas une preuve et ne doivent pas fonder seuls une sanction.',
'Outil d’analyse de similitudes et d’aide à l’intégrité académique. Distinguer similarité, citation légitime, plagiat et score de détection IA.',
'Plateforme d’intégrité académique. Examiner les passages et leurs sources ; conserver une procédure contradictoire pour toute décision.'
];
const uses={general:'Préparer une activité de 20 minutes sur la proportionnalité en 2e année collège à partir de vos objectifs.',research:'Comparer deux documents sur la gestion de l’eau au Maroc et retrouver la source de chaque chiffre.',prep:'Construire une séance de 55 minutes avec un objectif observable, une activité et un bilan.',eval:'Préparer cinq questions diagnostiques et expliquer les erreurs révélées par chaque distracteur.',visual:'Transformer un plan validé en six diapositives lisibles au vidéoprojecteur.',image:'Créer une scène fictive pour faire décrire un lieu en français, avec une mention « illustration générée ».',video:'Préparer une capsule de deux minutes, accompagnée d’une transcription imprimable.',interactive:'Recueillir trois hypothèses par groupe, puis discuter les divergences collectivement.',language:'Comparer deux traductions d’une consigne français–arabe et justifier le vocabulaire retenu.',math:'Comparer le graphique d’une fonction avec un tableau de valeurs calculé à la main.',access:'Tester une version aérée et une version lue d’un même texte, au choix de l’élève.',tutor:'Préparer un dialogue guidé avec des indices gradués, puis vérifier le transfert sans outil.',organize:'Structurer sa progression mensuelle à partir de notes de préparation sans informations sur les élèves.',detect:'Préparer un entretien où l’élève explique ses sources, ses brouillons et ses choix.'};
const readable=new Set([1,6,7,10,11,12,13,14,15,16,33]);
const resources=original.TOOLS.map((t,i)=>({id:slug(t.name),type:'outil',title:t.name,desc:toolDescriptions[i],category:cats[t.cat],objective:cats[t.cat],discipline:t.cat==='math'?'Mathématiques':t.cat==='language'?'Langues':'Toutes disciplines',level:'Collège et lycée',difficulty:'Débutant',language:'À vérifier',cost:i===1||i===6?'Freemium':'À vérifier',account:i===1||i===6||i===10?'Oui':'Selon usage, à vérifier',media:['image','visual','video','math','research','code'].includes(t.cat)?({image:'Image',visual:'Présentation',video:'Audio / vidéo',math:'Calcul',research:'Recherche',code:'Programmation'}[t.cat]):'Texte',link:t.link,example:uses[t.cat],benefits:['Un point de départ à adapter à votre classe.',t.cat==='access'?'Permet d’essayer plusieurs modalités de lecture.':'Peut faciliter une étape précise de la préparation.'],limits:[t.cat==='detect'?'Faux positifs et faux négatifs possibles. Plusieurs détecteurs ne forment pas une preuve.':'Ne garantit ni l’exactitude ni l’alignement au programme marocain.','Conditions d’accès, langues, quotas et tarifs à vérifier sur le site officiel.'],privacy:'Avant tout usage avec des élèves, faire valider le service par l’établissement. Vérifier la conservation, la réutilisation, la suppression et les transferts des données. Utiliser des exemples fictifs pour les essais.',checked:readable.has(i)?date:null,reviewed:date,verification:readable.has(i)?'Page officielle consultée ; usage principal revu. Conditions détaillées non auditées.':'Ressource conservée ; contrôle documentaire détaillé à poursuivre.',origin:'Fichier fourni',tags:[cats[t.cat],t.cat==='prep'?'préparation':'',t.cat==='visual'?'supports':'',t.cat==='tutor'?'élèves':''].filter(Boolean)}));
resources[0].id='chatgpt';resources[0].link='https://chatgpt.com/';
resources[11].title='Wayground (anciennement Quizizz)';resources[11].link='https://wayground.com/';
resources[13].link='https://www.canva.com/education/';resources[17].link='https://www.canva.com/education/';
resources[5].sources=[{title:'Aide Google : sources et réponses',url:'https://support.google.com/notebooklm/answer/17003757'}];resources[5].checked=date;
const addedTools=[
['Zotero','research','https://www.zotero.org/','Gestionnaire de références bibliographiques, complémentaire à l’IA. Classer ses sources et préparer une bibliographie.','Sauvegarder les documents utilisés pour une séquence d’histoire, puis vérifier les auteurs et dates.'],
['Semantic Scholar','research','https://www.semanticscholar.org/','Moteur de recherche de littérature scientifique. Lire les résumés et vérifier l’étude originale avant d’en tirer une conclusion pédagogique.','Rechercher des études sur le feedback et comparer le public étudié à votre classe.'],
['Elicit','research','https://elicit.com/','Assistant de recherche documentaire scientifique. Vérifier les publications identifiées, leurs méthodes et les passages sources.','Préparer un tableau comparatif de trois études sur la pratique espacée.'],
['Consensus','research','https://consensus.app/','Service de recherche dans la littérature scientifique. Les réponses agrégées ne remplacent pas la lecture critique des études.','Examiner une question sur les apprentissages sans confondre corrélation et causalité.'],
['GeoGebra','math','https://www.geogebra.org/','Outils de géométrie et de visualisation mathématique, complémentaires à l’IA générative.','Faire varier les coefficients d’une fonction affine et confronter les observations à une explication.'],
['PhET','open','https://phet.colorado.edu/fr/','Simulations interactives en sciences et mathématiques. Ressources complémentaires à l’IA.','Explorer un circuit simple avec une fiche d’hypothèses et un tableau d’observations.'],
['Scratch','code','https://scratch.mit.edu/','Environnement de programmation visuelle pour construire et expliquer un algorithme. Complément pédagogique à l’IA.','Tester un algorithme proposé par une IA en le reconstruisant bloc par bloc.'],
['Python Tutor','code','https://pythontutor.com/','Visualisation pas à pas de l’exécution de petits programmes. Ne pas utiliser de données ou de clés privées.','Suivre l’évolution d’une variable dans une boucle et expliquer un résultat inattendu.'],
['Mermaid','visual','https://mermaid.js.org/','Création de diagrammes à partir d’une description textuelle structurée. Complément à un assistant de rédaction.','Dessiner un organigramme de résolution et vérifier chaque branche avec un exemple.'],
['diagrams.net','visual','https://www.diagrams.net/','Éditeur de schémas pour retravailler manuellement une carte ou un processus proposé par une IA.','Mettre au propre une carte des arguments d’un débat de philosophie.'],
['OpenStax','open','https://openstax.org/','Manuels éducatifs ouverts à consulter et à adapter selon leur licence. Vérifier leur adéquation au niveau visé.','Comparer une explication de physique avec le chapitre de votre manuel de référence.'],
['Wikimedia Commons','open','https://commons.wikimedia.org/','Médiathèque collaborative. Consulter la licence et l’attribution de chaque fichier avant sa réutilisation.','Choisir une photographie documentaire authentique et rédiger une légende sourcée.']
];
for(const [name,cat,link,desc,example] of addedTools)resources.push({id:slug(name),type:'outil',title:name,category:cats[cat],objective:cats[cat],desc,example,link,discipline:cat==='math'?'Mathématiques':cat==='code'?'Informatique':'Toutes disciplines',level:'Collège et lycée',difficulty:cat==='code'?'Intermédiaire':'Débutant',language:'À vérifier',media:cat==='code'?'Programmation':cat==='visual'?'Diagramme':cat==='math'?'Calcul':'Recherche',cost:'À vérifier',account:'Selon usage, à vérifier',reviewed:date,checked:null,verification:'Lien de référence ; détails de l’offre à contrôler.',benefits:['Complète un travail de préparation avec des sources ou des représentations vérifiables.'],limits:['La sélection des ressources et l’adaptation pédagogique restent à la charge de l’enseignant.'],privacy:'Utiliser des exemples fictifs et consulter les conditions du service.',tags:[cats[cat]]});
const safety='\n\nContraintes : ne traite aucune donnée permettant d’identifier un élève. Appuie-toi sur le contenu et les objectifs que je fournis ; n’invente ni programme officiel, ni source. Signale ce qui manque. Je vérifierai les connaissances, le niveau, les droits d’usage et la faisabilité avant utilisation.';
for(const p of original.PROMPTS){let text=p.text;if(p.title.includes('protocole'))text+='\nNe propose pas de manipulation nouvelle non validée. Pars exclusivement d’un protocole de référence que je fournis. La sécurité doit être validée par l’enseignant et les consignes de l’établissement.';if(p.title.includes('Histoire'))text+='\nUtilise un document authentique fourni. Si tu écris un exemple fictif, étiquette-le explicitement et ne lui attribue aucun auteur réel.';resources.push({id:slug(p.title),type:'prompt',title:p.title,desc:'Un modèle à personnaliser pour '+p.catLabel.toLowerCase()+', avec résultat attendu et vérification par l’enseignant.',category:cats[p.cat],objective:cats[p.cat],discipline:p.title.startsWith('Math')?'Mathématiques':p.title.startsWith('Sciences')?'Sciences':p.title.startsWith('Histoire')?'Histoire-géographie':p.title.startsWith('Langues')?'Langues':'Toutes disciplines',level:'Collège et lycée',difficulty:'Débutant',language:'Français',media:'Texte',cost:'Gratuit',text:text+safety,example:'Matière : mathématiques ; niveau : 2e année collège ; thème : proportionnalité ; durée : 25 minutes. Remplacer ce contexte et joindre votre support validé.',expected:p.cat==='eval'?'Un sujet ou une grille dont les questions, critères et corrigés sont cohérents.':'Un document structuré, adapté aux paramètres saisis, à relire avant usage.',advice:'Préciser les acquis de la classe et le matériel disponible. Demander une seconde version en corrigeant un seul point à la fois.',reviewed:date,tags:[p.catLabel,'préparation','prompt']})}
const newPrompts=[
['Objectifs observables et critères de réussite','Préparation de cours','Toutes disciplines','À partir de [chapitre] et des attendus suivants [attendus validés], formule 3 objectifs observables pour [niveau]. Pour chacun, donne une production attendue, un critère de réussite et une activité de 10 minutes. Évite les verbes vagues comme « comprendre ».','Un tableau objectif / production / critère / activité.'],
['Préparer un débat argumenté','Argumentation','Philosophie','Prépare un débat de [durée] sur [question] pour [niveau]. Distingue thèse, argument, exemple et objection. Propose deux positions défendables, sans inventer de citations, une phase de préparation individuelle et une grille d’écoute. Utilise seulement [documents fournis].','Un déroulé de débat et une grille d’observation.'],
['Lecture critique d’un chiffre','Vérification','Histoire-géographie','Analyse ce chiffre avec sa source : [extrait et référence]. Identifie la population, la période, le territoire, l’unité, le dénominateur et les limites. Liste les informations absentes. Propose trois questions de lecture critique pour [niveau].','Une fiche de contrôle et trois questions sourcées.'],
['Feedback qui aide à réviser','Feedback','Français','Sur cette production fictive [texte], donne un point fort et deux actions de révision liées à [critères]. Cite les passages concernés. Pose une question qui aide l’élève à améliorer lui-même le texte. Ne réécris pas la production entière et n’attribue pas de note.','Trois retours précis et une question de révision.'],
['Fiche de révision et auto-test','Révision','Toutes disciplines','À partir de [cours autorisé], crée une fiche de révision pour [niveau] : cinq idées clés, trois erreurs fréquentes, six questions sans réponses puis un corrigé séparé. Ne complète pas les informations absentes.','Une fiche courte et un auto-test corrigé.'],
['Storyboard d’une capsule pédagogique','Supports & présentations','Toutes disciplines','Transforme [contenu validé] en storyboard de 120 secondes pour [niveau]. Fournis un tableau temps / narration / visuel / texte à l’écran. Prévois une transcription accessible et une question finale. N’imite aucune voix ou personne réelle.','Un storyboard minuté prêt à relire.'],
['Projet interdisciplinaire sur l’eau','Projet','Sciences','Conçois un projet de [nombre] séances pour [niveau] au Maroc autour de l’eau : sciences, mathématiques et langues. Pars de [sources locales vérifiées]. Prévois une question de recherche, un relevé sans données personnelles, une restitution et une évaluation du processus.','Un projet avec rôles, étapes et productions.'],
['Indices gradués en mathématiques','Remédiation','Mathématiques','Pour [problème] de niveau [niveau], propose trois indices successifs. Le premier doit aider à comprendre la consigne, le deuxième à choisir une méthode, le troisième à démarrer le calcul. Place la solution dans une partie séparée. Vérifie-la par une autre méthode.','Trois indices sans dévoilement immédiat.'],
['Déboguer en expliquant','Programmation','Informatique','Analyse ce court programme [code] et son résultat attendu [résultat]. Propose deux jeux de tests, repère l’erreur avec une explication adaptée à [niveau], puis pose une question avant de montrer la correction. N’exécute aucune instruction externe.','Des tests, une explication et une correction commentée.'],
['Analyser un tableau de données fictives','Recherche & documentation','Économie','Voici un tableau de données fictives [tableau]. Contrôle les unités et les valeurs manquantes, calcule [indicateur] en explicitant la formule, puis propose un graphique pertinent. N’invente pas les valeurs absentes.','Une analyse reproductible et ses limites.'],
['Étude de cas : comparer des offres','Évaluation','Économie','Crée une étude de cas fictive pour [niveau] comparant trois offres en dirhams. Fournis coûts fixes, coûts variables, contraintes et corrigé calculé. Demande une recommandation argumentée, pas seulement le prix le plus bas.','Un cas, un tableau de comparaison et un corrigé.'],
['Consigne bilingue français–arabe','Langues & traduction','Arabe','Reformule cette consigne [consigne] pour [niveau] en français simple puis en arabe standard. Présente un petit lexique des termes disciplinaires. Signale les traductions ambiguës et garde les mêmes exigences dans les deux langues.','Deux consignes équivalentes et un lexique à relire.'],
['حوار موجّه لفهم نص','Lecture','Arabe','أنت مساعد تربوي. انطلاقا من [نص أملك حق استعماله]، اقترح خمسة أسئلة متدرجة لتلاميذ [المستوى] بالمغرب: فهم مباشر، تفسير، ثم رأي معلل. ضع الأجوبة المقترحة في جزء منفصل، وحدد مواضع الاستشهاد من النص. لا تضف معلومات غير موجودة.','أسئلة متدرجة وأجوبة مرتبطة بالنص.'],
['English speaking practice with roles','Langues & traduction','Anglais','Design a [duration]-minute speaking activity for Moroccan [level] students about [topic]. Provide two role cards, six useful expressions, a model exchange and a simple peer feedback checklist. Keep the language at [CEFR level] and avoid stereotypes.','Role cards and an observation checklist.'],
['Grille d’évaluation du processus','Évaluation','Toutes disciplines','Crée une grille sur 20 pour [projet] : compréhension 6, justification 6, vérification des sources 4, révision et déclaration de l’IA 4. Décris quatre niveaux de réussite par critère. Ne récompense pas l’usage d’un outil payant.','Une grille critériée et vérifiable sur 20.'],
['Vérifier une réponse générée','Vérification','Toutes disciplines','Voici une réponse générée [réponse] et mes références [sources]. Découpe-la en affirmations vérifiables. Classe chacune : étayée, contredite, ou non vérifiable avec ces documents. Cite le passage source, sans compléter les références manquantes.','Un tableau d’audit affirmation / preuve / statut.'],
['Illustration fictive pour un cours','Images','Français','Décris une illustration fictive pour travailler [notion] avec [niveau]. Indique les éléments à représenter, la composition, les éléments à exclure et un texte alternatif. Évite les personnes réelles et tout signe faisant croire à une archive authentique.','Un brief d’illustration avec légende et texte alternatif.'],
['Carte mentale sans surcharge','Supports & présentations','Toutes disciplines','À partir de [cours], propose une carte mentale avec une idée centrale et cinq branches maximum. Relie chaque branche à un exemple du cours. Fournis aussi une version en liste hiérarchisée pour l’impression et l’accessibilité.','Une structure de carte et sa version textuelle.']
];
for(const [title,category,discipline,text,expected]of newPrompts)resources.push({id:slug(title)||'questions-arabe',type:'prompt',title,category,objective:category,discipline,level:'Collège et lycée',difficulty:'Intermédiaire',language:title.startsWith('حوار')?'Arabe':title.startsWith('English')?'Anglais':'Français',cost:'Gratuit',media:'Texte',text:text+safety,expected,example:discipline==='Arabe'?'Niveau : 3e année collège ; support : un texte court autorisé ; durée : 20 minutes.':'Exemple de contexte : tronc commun, 30 minutes, classe hétérogène, travail en groupes avec une restitution sur papier.',advice:'Remplacer chaque variable par votre contexte. Comparer le résultat au support de référence et demander une correction ciblée.',reviewed:date,tags:[category,discipline,'prompt']});
for(const [i,t]of original.TUTOS.entries()){
 const steps=t.steps.map(s=>({...s}));
 if(i===2){steps[0]={t:'Utiliser un texte fictif ou réellement anonymisé',d:'Enlever un nom ne suffit pas : retirer aussi les détails indirectement identifiants. Pour un essai, préférer une production fictive. Faire valider le traitement de copies réelles par l’établissement.'}}
 if(i===3){steps[1]={t:'Recueillir des traces du travail',d:'Comparer le brouillon, les sources et les révisions, sans assimiler un changement de style à une fraude.'};steps[2]={t:'Écarter la fausse certitude des scores',d:'Croiser des détecteurs peut reproduire les mêmes erreurs. Leur convergence ne démontre pas une fraude. Privilégier les preuves du processus et le dialogue.'};steps[3]={t:'Inviter l’élève à expliquer ses choix',d:'Proposer une explication orale ou écrite équitable, adaptée aux besoins de l’élève. Lui permettre de présenter sa démarche.'}}
 if(i===4){steps[2]={t:'Interroger des documents autorisés',d:'Importer uniquement les extraits dont vous pouvez légalement faire cet usage. Exiger des citations et comparer chaque réponse au passage source ; des erreurs restent possibles.'};steps[4]={t:'Vérifier les droits avant l’importation et le partage',d:'L’usage pédagogique interne n’autorise pas automatiquement toute reproduction ou tout envoi à un service externe. Vérifier la licence, l’autorisation et le cadre applicable.'}}
 if(i===6)steps[4]={t:'Organiser une participation équitable',d:'Utiliser un appareil par groupe si cela est autorisé. Sinon, projeter les questions et recueillir les réponses sur papier. Ne pas exiger la création de comptes personnels.'};
 resources.push({id:slug(t.title),type:'tutoriel',title:t.title.replace(/en 15 minutes/,'pas à pas').replace(/en 5 minutes/,'pas à pas'),desc:t.objective,category:cats[t.cat],objective:cats[t.cat],discipline:t.cat==='math'?'Mathématiques':'Toutes disciplines',level:'Collège et lycée',difficulty:t.diff==='debutant'?'Débutant':'Intermédiaire',language:'Français',cost:'Gratuit',media:t.cat==='visual'?'Présentation':'Texte',duration:t.duration+' de préparation indicative',tools:t.tools,steps,expected:t.result,pitfall:t.pitfall,reviewed:date,tags:[cats[t.cat],'préparation','tutoriel']});
}
const scenarios=[
['Une solution juste… pour de mauvaises raisons','Mathématiques','2e année collège',55,'Proportionnalité','Distinguer calcul correct et justification valable.','Une solution fictive affirme que 3 cahiers coûtent 18 DH et que 5 cahiers coûtent 30 DH, mais utilise une règle additive incorrecte dans son explication.','Préparer deux explications dont une contient une erreur de méthode, puis vérifier soi-même tous les calculs.','10 min : résolution individuelle sans IA.|15 min : comparaison en binômes de deux solutions imprimées.|20 min : correction argumentée et contre-exemple.|10 min : nouveau problème sans aide.','L’élève identifie l’étape incorrecte, produit un contre-exemple et justifie la bonne méthode.','Une solution correcte ne prouve pas que la méthode est comprise.','indices-gradues-en-mathematiques'],
['Réviser un paragraphe sans déléguer sa voix','Français','Tronc commun',55,'Feedback','Améliorer une argumentation en justifiant ses révisions.','Un paragraphe fictif défend l’intérêt d’un club de lecture dans un lycée.','Rédiger un texte de départ fictif et préparer un feedback en trois points.','10 min : première lecture et diagnostic.|15 min : comparaison du feedback du professeur et de l’IA.|20 min : révision individuelle.|10 min : justification de deux changements.','Évaluer la pertinence des modifications et leur justification, sans compter mécaniquement les erreurs.','Ne pas envoyer les copies nominatives à un service externe.','feedback-qui-aide-a-reviser'],
['قراءة نقدية لإجابة مولّدة','Arabe','3e année collège',50,'Lecture','Repérer une interprétation qui n’est pas soutenue par le texte.','Une réponse en arabe standard interprète un court texte narratif autorisé.','Préparer le texte, numéroter ses lignes et écrire une interprétation volontairement discutable.','10 min : lecture individuelle.|15 min : repérage des affirmations.|15 min : justification avec les lignes du texte.|10 min : rédaction d’une réponse corrigée.','Chaque justification s’appuie sur un passage précis et distingue fait et interprétation.','Ne pas transformer une interprétation subjective en seule réponse admise.','questions-arabe'],
['An AI dialogue, made our own','Anglais','1re année baccalauréat',55,'Expression orale','Adapter un dialogue et interagir sans lire un script.','Deux élèves simulent une demande d’information dans une bibliothèque.','Préparer deux cartes de rôle et six expressions adaptées aux acquis de la classe.','10 min : repérage des expressions.|15 min : adaptation en binômes.|20 min : jeux de rôles avec changement de contrainte.|10 min : retour et auto-évaluation.','Observer la compréhension du partenaire, l’adaptation et la réutilisation pertinente du lexique.','Un accent différent ne doit pas être assimilé à une mauvaise compréhension.','english-speaking-practice-with-roles'],
['Un schéma électrique à mettre à l’épreuve','Physique-chimie','3e année collège',55,'Vérification scientifique','Confronter une représentation à un modèle scientifique.','La classe compare deux schémas de circuits simples, dont l’un est incohérent.','Valider les schémas à partir du manuel et préparer une simulation ou des dessins papier.','10 min : prédictions.|15 min : examen des connexions.|20 min : simulation guidée ou raisonnement collectif.|10 min : schéma corrigé et explication.','L’élève explique le circuit et justifie la correction à partir du modèle étudié.','Aucune manipulation électrique nouvelle : suivre uniquement les protocoles validés de l’établissement.','verifier-une-reponse-generee'],
['Lire une information sur l’eau avec méthode','SVT','Tronc commun',55,'Recherche documentaire','Distinguer observation, explication et affirmation non sourcée.','Deux documents autorisés traitent de l’eau et des écosystèmes au Maroc.','Choisir des documents datés et préparer un résumé contenant une omission repérable.','10 min : hypothèses.|15 min : lecture par groupes.|20 min : audit du résumé.|10 min : conclusion sourcée.','Une fiche relie chaque affirmation importante à sa preuve et signale les limites.','Ne pas confondre une situation locale avec une généralité nationale.','lecture-critique-d-un-chiffre'],
['Un chiffre sur le Maroc : que dit-il vraiment ?','Histoire-géographie','1re année baccalauréat',55,'Esprit critique','Interpréter une statistique avec son périmètre et sa source.','Un tableau officiel daté est comparé à une synthèse fictive trop générale.','Choisir une publication du HCP et isoler un tableau lisible avec sa méthodologie.','10 min : lecture du graphique.|15 min : identification du champ et des unités.|20 min : correction de la synthèse.|10 min : rédaction d’une légende.','La légende précise date, unité, population et source sans extrapolation.','Ne pas présenter les données d’un échantillon comme une mesure de tous les élèves.','lecture-critique-d-un-chiffre'],
['L’IA peut-elle être une autorité ?','Philosophie','2e année baccalauréat',55,'Argumentation','Évaluer un argument indépendamment de son auteur supposé.','Deux argumentaires fictifs sur la vérité et l’autorité sont soumis à la classe.','Choisir un extrait autorisé du corpus de cours, sans inventer de citation de philosophe.','10 min : position individuelle.|15 min : reconstruction des arguments.|20 min : débat avec objections.|10 min : synthèse nuancée.','L’élève formule un argument, répond à une objection et mobilise une référence effectivement étudiée.','Annoncer que les argumentaires sont fictifs et distinguer opinion et thèse du corpus.','preparer-un-debat-argumente'],
['Déboguer une boucle, expliquer chaque étape','Informatique','Tronc commun',55,'Programmation','Relier une sortie du programme à son exécution.','Un court programme Python comporte une erreur de borne dans une boucle.','Préparer le code, le résultat attendu et trois jeux de tests ; vérifier dans un environnement local.','10 min : prédiction sur papier.|15 min : trace des variables.|20 min : correction en binômes.|10 min : transfert à un second programme.','Évaluer la trace, le test choisi et l’explication de la correction.','Ne jamais exécuter du code inconnu ayant accès aux fichiers ou au réseau.','deboguer-en-expliquant'],
['Choisir une offre et défendre sa décision','Économie','1re année baccalauréat',55,'Décision argumentée','Comparer un coût total et expliciter une hypothèse.','Trois offres fictives en dirhams comportent un abonnement et un coût à l’usage.','Vérifier les tableaux et annoncer explicitement que les prix sont fictifs.','10 min : lecture des contraintes.|15 min : calculs.|20 min : recommandation argumentée.|10 min : changement d’hypothèse.','Une décision justifiée par un calcul reproductible et ses limites.','Ne pas utiliser de tarifs fictifs pour conseiller un achat réel.','etude-de-cas-comparer-des-offres'],
['Un cahier des charges à clarifier','Sciences de l’ingénieur','2e année baccalauréat',55,'Conception','Transformer une demande vague en critères mesurables.','Une demande fictive décrit un système d’éclairage automatique de maquette.','Préparer le besoin, les contraintes autorisées et une proposition IA volontairement incomplète.','10 min : analyse fonctionnelle.|15 min : identification des exigences manquantes.|20 min : tableau de critères.|10 min : revue croisée.','Chaque critère est mesurable et relié au besoin initial.','Aucun montage non validé ; garder l’activité au niveau du cahier des charges.','objectifs-observables-et-criteres-de-reussite'],
['Une enquête documentaire interdisciplinaire','Toutes disciplines','Collège et lycée',110,'Projet','Construire une synthèse collective dont les affirmations sont traçables.','La classe explore une question locale liée à l’eau avec un corpus public préparé.','Sélectionner trois sources autorisées et préparer une fiche commune de lecture.','20 min : formulation des questions.|30 min : lecture et relevé de preuves.|40 min : production d’une affiche sourcée.|20 min : restitution et réflexion sur l’usage de l’IA.','Évaluer la qualité des sources, la coopération, la vérification et la restitution.','Ne collecter aucune information personnelle auprès d’habitants ou d’élèves.','projet-interdisciplinaire-sur-l-eau']
];
for(const [title,discipline,level,minutes,category,desc,context,prep,run,evaluation,vigilance,prompt]of scenarios)resources.push({id:slug(title),type:'scenario',title,desc,discipline,level,minutes,duration:minutes+' min',category,objective:category,difficulty:'Intermédiaire',language:discipline==='Arabe'?'Arabe':discipline==='Anglais'?'Anglais':'Français',cost:'Gratuit',media:'Texte',audience:'Enseignant ; élèves sans compte IA',context,prerequisites:'Avoir travaillé la notion visée et savoir justifier une réponse à partir d’un document ou d’un calcul.',materials:'Tableau, feuilles et documents imprimés. Un ordinateur enseignant est utile pour préparer ; la séance peut se dérouler sans connexion.',preparation:prep,steps:run.split('|').map(x=>({t:x.split(':')[0],d:x.slice(x.indexOf(':')+1).trim()})),roles:{teacher:'Choisit les documents, valide les productions, anime les échanges et évalue les apprentissages.',ai:'Propose un support de travail préparé en amont ; ne décide ni des objectifs ni des notes.',students:'Analysent, discutent, vérifient et produisent une réponse personnelle argumentée.'},evaluation,pitfall:vigilance,variants:'Avec peu de temps, limiter la comparaison à un extrait. Avec une classe avancée, faire concevoir un contre-exemple et expliquer ses limites.',related:[prompt,'verifier-une-reponse-generee'],reviewed:date,tags:[discipline,category,'élèves','sans connexion','scénario']});
const terms=[
['Intelligence artificielle','Ensemble de méthodes informatiques qui réalisent des tâches telles que classer, prédire, reconnaître ou produire du contenu.','Un système classe des images ; un autre propose un texte.'],
['IA générative','Système qui produit un contenu nouveau à partir d’une demande et de régularités apprises.','Générer plusieurs formulations d’une consigne puis choisir la plus claire.'],
['Prompt','Demande adressée à un système d’IA. Un bon cadrage aide, sans garantir une réponse exacte.','Indiquer le niveau, la durée, le support et le format souhaité.'],
['Hallucination','Production erronée ou inventée présentée de façon plausible par une IA.','Une bibliographie contient un article qui n’existe pas.'],
['LLM','Grand modèle de langage entraîné notamment à prédire et produire des séquences de tokens.','Un assistant rédige une explication à partir d’une consigne.'],
['Token','Unité de représentation du texte ou d’un autre contenu utilisée par un modèle ; ce n’est pas nécessairement un mot.','Un mot arabe ou français peut être représenté par plusieurs tokens.'],
['Fenêtre de contexte','Quantité de contenu qu’un modèle peut prendre en compte dans une interaction.','Un long dossier peut dépasser les limites du service.'],
['Multimodal','Qui traite ou produit plusieurs types de contenu : texte, image, audio, etc.','Poser une question sur un schéma joint.'],
['RAG','Méthode qui récupère des passages de documents pour aider un modèle à produire une réponse. Elle ne supprime pas toutes les erreurs.','Retrouver un passage de cours avant de répondre à une question.'],
['Biais algorithmique','Tendance systématique qui peut défavoriser certains groupes ou points de vue.','Des exemples associent toujours le même métier à un genre.'],
['Deepfake','Média synthétique ou modifié pouvant faire croire qu’une personne a dit ou fait quelque chose.','Une fausse vidéo attribue une annonce à une personne réelle.'],
['Fine-tuning','Adaptation d’un modèle existant par un entraînement supplémentaire.','Spécialiser un modèle sur un type de tâche avec des données autorisées.'],
['Agent','Système qui enchaîne des actions avec des outils en poursuivant un objectif.','Chercher des documents puis préparer un tableau de synthèse, avec validation humaine.'],
['Entraînement','Processus qui ajuste les paramètres d’un modèle à partir de données et d’objectifs.','Apprendre des régularités linguistiques dans un grand corpus.'],
['Inférence','Utilisation d’un modèle entraîné pour produire un résultat.','Envoyer un prompt et recevoir une réponse.'],
['Raisonnement généré','Suite d’explications ou d’étapes produites par un modèle ; elle peut sembler logique et contenir des erreurs.','Une résolution affiche des étapes dont il faut contrôler la validité.'],
['Recherche web','Consultation de sources accessibles en ligne ; elle doit être réellement disponible et activée dans l’outil.','Demander une information récente puis ouvrir le communiqué original.'],
['Donnée personnelle','Information se rapportant à une personne identifiée ou identifiable.','Un nom, une photo ou une combinaison de détails sur un élève.'],
['Pseudonymisation','Remplacement d’identifiants par un code, sans forcément empêcher la réidentification.','« Élève A » reste identifiable si le texte décrit sa situation unique.'],
['Anonymisation','Transformation visant à empêcher l’identification d’une personne, y compris par recoupement.','Utiliser un exemple entièrement fictif pour tester un feedback.'],
['Droit d’auteur','Cadre qui protège certaines créations et encadre leur utilisation ; les droits et exceptions dépendent du contexte juridique.','Vérifier la licence d’un texte avant de l’importer dans un outil.'],
['Modèle ouvert','Modèle dont certains éléments sont accessibles ; les droits de réutilisation dépendent de sa licence.','Vérifier la licence même si les poids sont téléchargeables.'],
['Modèle propriétaire','Modèle contrôlé par un fournisseur selon ses conditions d’accès et d’usage.','Accéder à un modèle par un abonnement ou une interface web.'],
['Traçabilité','Possibilité de retrouver l’origine d’une information et les étapes de production.','Joindre sources, brouillons et déclaration d’usage de l’IA à un projet.'],
['Évaluation formative','Évaluation utilisée pour ajuster l’apprentissage en cours.','Un quiz court sert à choisir la prochaine activité de remédiation.']
];
for(const [title,desc,example]of terms)resources.push({id:'glossaire-'+slug(title),type:'concept',title,desc,example,category:'Comprendre l’IA',objective:'Comprendre l’IA',discipline:'Toutes disciplines',level:'Collège et lycée',difficulty:'Débutant',language:'Français',cost:'Gratuit',media:'Texte',reviewed:date,tags:['glossaire',title]});
const sourceRows=original.SOURCES.map(s=>({title:s.name,link:s.url,desc:s.desc}));
sourceRows[0].desc='Portail UNESCO sur l’IA dans l’éducation. Référence internationale à contextualiser au Maroc.';
sourceRows[1].desc='Recommandation internationale de 2021 sur l’éthique de l’IA ; ne constitue pas une loi marocaine.';
sourceRows[4].desc='Point de départ pour retrouver les publications et documents officiels de l’éducation au Maroc.';
sourceRows[5].desc='Communiqué du ministère sur sa participation au lancement de la feuille de route « AI Made in Morocco », le 12 janvier 2026.';
sourceRows[6].desc='Site officiel du CSEFRS. Consulter les publications originales ; les affirmations du fichier initial sur une recommandation d’avril 2026 ne sont pas reprises faute de vérification directe.';
sourceRows[7].desc='Autorité française de protection des données : référence comparative, distincte de la CNDP marocaine.';
sourceRows[9].desc='Article de presse conservé pour la veille. Source secondaire : vérifier les textes et chiffres dans les documents originaux.';
sourceRows[10].desc='Article de presse conservé. Les chiffres du fichier initial ne sont pas reproduits faute de contrôle dans la source primaire.';
sourceRows.push(
{title:'CNDP — Conditions de traitement',link:'https://www.cndp.ma/conditions/',desc:'Repères officiels sur la finalité, la proportionnalité et la qualité des données, au titre de la loi 09-08.',checked:date},
{title:'CNDP — Transfert de données à l’étranger',link:'https://www.cndp.ma/wp-content/uploads/2023/12/CNDP-Transfert-Etranger.pdf',desc:'Formulaire officiel relatif aux articles 43 et 44 de la loi 09-08. Faire examiner les formalités applicables au traitement envisagé.',checked:date},
{title:'WIPO Lex — Droit d’auteur au Maroc',link:'https://www.wipo.int/wipolex/en/text/567222',desc:'Version de la loi 2-00 indiquée comme modifiée jusqu’à la loi 79-12. Vérifier les modifications ultérieures avant une décision juridique.',checked:date},
{title:'UNESCO — Compétences IA des enseignants',link:'https://www.unesco.org/en/articles/ai-competency-framework-teachers',desc:'Référentiel publié en 2024 pour structurer la formation des enseignants à l’IA.',checked:date},
{title:'UNICEF — IA et droits de l’enfant',link:'https://www.unicef.org/innocenti/projects/policy-guidance-ai-children',desc:'Référence internationale pour examiner les effets des systèmes d’IA sur les enfants.'},
{title:'Commission européenne — IA et données en éducation',link:'https://education.ec.europa.eu/focus-topics/digital-education/action-plan/action-6',desc:'Référence européenne pour enseignants ; portée distincte du cadre juridique marocain.'},
{title:'HCP — Données publiques marocaines',link:'https://www.hcp.ma/',desc:'Source institutionnelle pour des études de documents et activités de lecture de données.'},
{title:'Elements of AI — Formation introductive',link:'https://www.elementsofai.com/',desc:'Parcours introductif à explorer en autoformation. Langues et accès à vérifier.'},
{title:'FUN MOOC — Catalogue de formations',link:'https://www.fun-mooc.fr/',desc:'Catalogue à consulter pour des formations sur le numérique et l’IA. Dates de session à vérifier.'}
);
sourceRows[5].checked=date;
for(const s of sourceRows)resources.push({id:slug(s.title),type:'source',...s,category:s.title.includes('CNDP')||s.title.includes('WIPO')?'Cadre juridique & éthique':s.title.includes('Formation')||s.title.includes('MOOC')?'Formation':'Sources & veille',objective:'Recherche & documentation',discipline:'Toutes disciplines',level:'Collège et lycée',difficulty:'Intermédiaire',language:s.title.includes('WIPO')?'Anglais':'Français',cost:'À vérifier',media:'Recherche',reviewed:date,verification:s.checked?'Source primaire consultée.':'Référence conservée ou ajoutée ; vérification détaillée à poursuivre.',tags:['sources','veille',s.title]});
const guides=[
['Protéger les données avant un premier essai','Cadre juridique & éthique','Une méthode de préparation pour éviter d’exposer des informations sur les élèves.',['Définir le besoin : quel contenu est réellement nécessaire pour préparer cette activité ?','Choisir un exemple fictif : enlever un nom ne suffit pas à anonymiser un récit ou une copie.','Faire vérifier le service et le traitement par le responsable compétent de l’établissement. Examiner la finalité, l’accès, la conservation et les transferts.','Conserver la version du support utilisée et la trace de votre validation.'],['cndp-conditions-de-traitement','cndp-transfert-de-donnees-a-l-etranger']],
['Déclarer l’usage de l’IA dans un travail','IA avec les élèves','Un modèle simple pour rendre les usages visibles sans approche uniquement punitive.',['Outil et date : indiquer le service et le jour d’utilisation.','Aide demandée : décrire la tâche confiée et fournir un prompt représentatif.','Apport personnel : indiquer ce qui a été retenu, rejeté ou réécrit.','Vérification : citer les sources ouvertes et les contrôles réalisés.'],['grille-d-evaluation-du-processus']],
['Adapter une évaluation à l’ère de l’IA','Évaluation','Observer la compréhension, les décisions et les révisions, au-delà du seul produit final.',['Annoncer ce qui est autorisé, à quel moment et avec quelles traces.','Prévoir une première étape en classe sans assistance pour observer les acquis.','Recueillir un brouillon commenté et une justification de deux choix.','Combiner un rendu final avec une courte explication, orale ou écrite selon les besoins.','Utiliser une grille commune qui ne favorise pas les élèves équipés d’outils payants.'],['grille-d-evaluation-du-processus','declarer-l-usage-de-l-ia-dans-un-travail']],
['Un bon prompt en six repères','Préparation de cours','Contexte, objectif, source, contraintes, format et vérification : un cadre réutilisable.',['Contexte : discipline, niveau marocain, acquis et durée.','Objectif : ce que les élèves devront pouvoir faire.','Source : joindre un extrait autorisé et distinguer source de consigne.','Contraintes : matériel, langue, hétérogénéité et temps.','Format : demander une fiche, un tableau ou une liste avec les rubriques utiles.','Vérification : exiger les incertitudes, contrôler le fond et relancer sur un point précis.'],['objectifs-observables-et-criteres-de-reussite','verifier-une-reponse-generee']],
['Vérifier sans se fier à l’assurance de l’IA','Vérification','Une vérification courte mais concrète pour préparer un support de classe.',['Isoler chaque affirmation factuelle.','Ouvrir la source originale et vérifier auteur, date et contexte.','Refaire les calculs et confronter les définitions au cours.','Distinguer un exemple fictif d’une donnée ou d’un document authentique.','Réécrire ce qui est incertain ou l’écarter de la séance.'],['verifier-une-reponse-generee','lecture-critique-d-un-chiffre']],
['Faire classe avec peu de connexion','Accessibilité','Préparer avec l’IA en amont et garder une activité réalisable pour tous.',['Préparer les supports depuis un poste enseignant autorisé.','Exporter la fiche et son corrigé en format imprimable.','Prévoir un exemplaire par groupe plutôt qu’un compte par élève.','Recueillir les réponses sur papier et discuter les méthodes au tableau.','Proposer une ressource audio seulement avec une transcription équivalente.'],['une-solution-juste-pour-de-mauvaises-raisons']],
['Choisir un outil sans se disperser','Productivité','Un essai comparatif basé sur une vraie tâche pédagogique.',['Définir une tâche fréquente et un résultat attendu.','Comparer deux services avec le même contenu fictif.','Mesurer la qualité du résultat et le temps de correction, pas seulement la vitesse de génération.','Contrôler l’export, la langue et la possibilité de faire la séance sans compte élève.','Vérifier les conditions du service avant de l’adopter.'],['chatgpt','claude']],
['Droit d’auteur : avant de copier un document','Cadre juridique & éthique','Points à examiner avant un import, une adaptation ou une diffusion.',['Identifier l’auteur, l’éditeur et la licence du document.','Distinguer lecture, reproduction, adaptation, import dans un service et publication.','Vérifier l’autorisation ou l’exception applicable à l’usage précis. Le seul objectif pédagogique n’autorise pas automatiquement tout usage.','Privilégier ses propres contenus, le domaine public vérifié ou une licence compatible.','Conserver l’attribution et les conditions de réutilisation.'],['wipo-lex-droit-d-auteur-au-maroc','wikimedia-commons']],
['Biais : relire aussi les exemples','IA avec les élèves','Une grille de discussion pour repérer les représentations répétitives ou excluantes.',['Repérer qui parle, agit et décide dans les exemples.','Varier les contextes marocains sans réduire les personnes à des stéréotypes.','Comparer une proposition en français et en arabe sans supposer leur équivalence.','Demander aux élèves quels points de vue manquent et pourquoi.'],['glossaire-biais-algorithmique']],
['Former un petit groupe de collègues','Formation','Un atelier de 60 minutes avec un objectif concret et une trace réutilisable.',['10 min : choisir une tâche et établir un résultat attendu.','15 min : tester un prompt avec des données fictives.','20 min : comparer les productions et documenter les corrections.','10 min : discuter données, droits et équité.','5 min : partager une fiche révisée avec date et sources.'],['unesco-competences-ia-des-enseignants','un-bon-prompt-en-six-reperes']]
];
for(const [title,category,desc,steps,related]of guides)resources.push({id:slug(title),type:'guide',title,desc,category,objective:category,discipline:'Toutes disciplines',level:'Collège et lycée',difficulty:'Débutant',language:'Français',cost:'Gratuit',media:'Texte',steps:steps.map((s,i)=>({t:'Repère '+(i+1),d:s})),related,reviewed:date,tags:[category,'bonnes pratiques','élèves']});
for(const r of resources){if(!r.id)r.id='lecture-critique-en-arabe';r.slug=r.id;r.status=r.checked?'source-consultee':r.type==='outil'||r.type==='source'?'a-revalider':'contenu-editorial';r.related=r.related||[];r.tags=r.tags||[];r.translations={};}
for(const r of resources){
 if(r.type==='tutoriel'){
  r.steps=r.steps.map(s=>({...s,d:s.d.replace(/du chapitre 04/g,'de la bibliothèque de prompts').replace(/au chapitre 04/g,'dans la bibliothèque de prompts').replace(/voir chapitre 07/g,'voir le cadre juridique et éthique').replace(/Voir le chapitre 02/g,'Voir le guide des prompts'),tip:s.tip?.replace('c’est le choix le plus sûr contre les hallucinations','vérifiez malgré tout chaque affirmation')}));
  if(r.title.includes('séquence différenciée'))r.desc='Passer d’un thème de cours à une proposition de séquence, puis adapter les aides et vérifier les objectifs.';
 }
 if(['zotero','geogebra','deepl-traducteur','wolfram-alpha','mathpix','kahoot','wooclap','ideogram','capcut-ai','nearpod','photomath','speechify','gptzero','compilatio','elicit'].includes(r.id)){r.checked=date;r.status='source-consultee';r.verification='Page officielle consultée ; usage principal revu. Offre et conditions détaillées à vérifier.';}
 if(r.id==='zotero'){r.cost='Gratuit';r.account='Pas nécessaire pour un usage local ; synchronisation avec compte';}
 if(r.id==='geogebra'){r.cost='Gratuit';r.account='Selon usage ; compte pour enregistrer en ligne';}
 if(r.id==='chatgpt-images-gemini')r.link='https://chatgpt.com/';
 if(r.language==='Arabe'&&r.type==='prompt')r.text=r.text.replace(safety,'\n\nلا تستعمل أي معطيات تسمح بالتعرف على تلميذ. اعتمد فقط على الأهداف والوثائق التي أقدمها، ولا تخترع مراجع أو توجيهات رسمية. حدد المعلومات الناقصة؛ سأتحقق من الدقة والملاءمة قبل الاستعمال.');
 if(r.language==='Anglais'&&r.type==='prompt')r.text=r.text.replace(safety,'\n\nUse no personally identifying student information. Work from the goals and material I provide; do not invent official curricula or sources. Identify missing information. I will check accuracy, level and suitability before use.');
}
const moreTutorials=[
['Analyser un tableau sans exposer les élèves','Recherche & documentation','Intermédiaire',['Tableur','Assistant au choix'],'Produire une analyse reproductible d’un tableau fictif ou public.',[
['Préparer un tableau de démonstration','Utiliser des données fictives ou publiques, avec unités et période. Ne pas importer un export de notes ou de présences.'],['Contrôler les données','Repérer les valeurs manquantes, doublons et unités incompatibles.'],['Demander une analyse limitée','Demander une formule précise, un calcul détaillé et une proposition de graphique.'],['Recalculer dans le tableur','Vérifier la formule sur trois lignes et comparer les totaux.'],['Documenter les limites','Ajouter une légende précisant source, date et champ. Ne pas extrapoler au-delà des données.']],'Un tableau contrôlé et un graphique accompagné de sa source.','analyser-un-tableau-de-donnees-fictives'],
['Produire une capsule vidéo avec sa transcription','Supports & présentations','Intermédiaire',['CapCut','Canva'],'Passer d’un contenu validé à une capsule courte et accessible.',[
['Fixer un seul objectif','Choisir une notion déjà vérifiée et une question finale de compréhension.'],['Écrire un storyboard','Limiter la narration à deux minutes. Décrire chaque plan sans image inutile.'],['Rassembler des médias autorisés','Vérifier les licences et conserver les attributions. Éviter les visages ou voix réels non autorisés.'],['Monter et sous-titrer','Assembler les plans, ajouter des sous-titres et corriger leur transcription.'],['Tester avant diffusion','Visionner avec et sans son. Fournir une transcription et un fichier de secours compatible.']],'Une capsule vérifiée et une transcription équivalente.','storyboard-d-une-capsule-pedagogique'],
['Expliquer un programme avec des tests','Programmation','Intermédiaire',['Python Tutor','Assistant au choix'],'Transformer une proposition de code en activité de compréhension.',[
['Choisir un programme court','Définir entrées, sorties attendues et notions déjà étudiées.'],['Prédire avant l’exécution','Demander aux élèves de tracer les variables sur papier.'],['Créer trois tests','Inclure un cas normal, un cas limite et une entrée invalide.'],['Examiner le code','Contrôler les opérations ; ne pas exécuter de code non fiable avec accès aux fichiers ou au réseau.'],['Expliquer la correction','Faire justifier chaque changement, puis proposer un nouveau cas sans aide.']],'Une trace d’exécution, des tests et une correction expliquée.','deboguer-en-expliquant'],
['Construire un dossier de réponses traçables','Recherche & documentation','Avancé',['NotebookLM','Zotero'],'Organiser plusieurs documents et contrôler la traçabilité des réponses.',[
['Définir le corpus','Choisir trois documents autorisés, datés, avec leur auteur et leur périmètre.'],['Tenir une table des sources','Associer un identifiant à chaque document et noter ses pages utiles.'],['Formuler une question délimitée','Demander une réponse basée sur le corpus avec références précises et signalement des lacunes.'],['Auditer les citations','Ouvrir chaque passage cité. Classer les affirmations comme étayées, contredites ou non vérifiables.'],['Tester une question sans réponse','Poser une question absente du corpus : une réponse assurée non sourcée signale une limite à discuter.'],['Produire la synthèse validée','Retirer les affirmations non étayées et conserver les liens vers les preuves.']],'Une synthèse dont chaque affirmation centrale est reliée à un passage vérifié.','verifier-une-reponse-generee']
];
for(const [title,category,difficulty,tools,desc,steps,expected,prompt]of moreTutorials)resources.push({id:slug(title),slug:slug(title),type:'tutoriel',title,category,objective:category,difficulty,tools,desc,steps:steps.map(([t,d])=>({t,d})),expected,pitfall:'Ne pas diffuser le résultat avant le contrôle des connaissances, des sources et des droits d’usage.',discipline:category==='Programmation'?'Informatique':'Toutes disciplines',level:'Collège et lycée',language:'Français',media:category==='Programmation'?'Programmation':category==='Supports & présentations'?'Audio / vidéo':'Recherche',duration:'25 à 40 min de préparation indicative',cost:'Gratuit',reviewed:date,status:'contenu-editorial',tags:[category,'préparation'],related:[prompt],translations:{}});
module.exports={resources,original,date,slug,cats};
