module.exports=(R,base)=>{
const rows=[
['temperature','Température','Réglage qui influence la variabilité du choix des tokens dans certains modèles.','Comparer deux propositions d’activité issues du même contexte.','Les interfaces n’exposent pas toutes ce réglage.','Une faible température ne garantit pas la vérité.','Variabilité et exactitude sont deux propriétés différentes.'],
['memoire','Mémoire','Fonction d’un service qui conserve certaines informations pour des échanges ultérieurs, selon ses réglages.','Un enseignant retrouve une préférence de format enregistrée.','Elle est distincte du contexte temporaire et varie selon le service.','Une information personnelle peut persister au-delà d’une conversation.','Examiner ce qui est conservé et les moyens de le supprimer.'],
['generation-images','Génération d’images','Production d’images à partir d’une consigne ou d’autres contenus.','Créer une illustration fictive puis rédiger sa légende.','Les détails, textes et relations spatiales peuvent être incorrects.','Une image réaliste peut induire en erreur sur un événement.','Signaler l’illustration et vérifier droits, personnes et informations.'],
['generation-audio','Génération audio','Production de parole, musique ou sons à partir d’une demande.','Préparer une lecture d’un dialogue fictif et sa transcription.','Prononciation, rythme et sens peuvent être altérés.','Imiter une voix réelle peut tromper ou porter atteinte à une personne.','Privilégier une voix synthétique générique et un texte autorisé.'],
['generation-video','Génération vidéo','Production ou transformation de séquences animées à partir de consignes.','Illustrer un phénomène avec une animation identifiée comme simulation.','La cohérence temporelle et la physique peuvent échouer.','Une animation convaincante peut enseigner un mécanisme faux.','La validation scientifique précède la projection.'],
['ia-traditionnelle','IA à règles, IA prédictive, IA générative','Des systèmes appliquent des règles, prédisent une classe ou produisent du contenu ; ces familles peuvent se combiner.','Comparer une règle de tri, un classifieur appris et un générateur de descriptions.','« Traditionnelle » regroupe des techniques différentes, pas une seule architecture.','Présenter toute automatisation comme une IA masque les mécanismes réels.','Identifier la tâche et la méthode avant de choisir l’étiquette.'],
['donnees-entrainement','Données d’entraînement','Exemples utilisés pour ajuster les paramètres d’un modèle.','Construire un petit corpus fictif et observer les catégories absentes.','Un corpus incomplet peut limiter ce que le modèle apprend.','Des représentations déséquilibrées peuvent se retrouver dans les sorties.','Demander quelles données et quels tests soutiennent l’usage.'],
['chatbot','Chatbot','Interface de dialogue pouvant utiliser des règles, un modèle de langage ou plusieurs outils.','Poser une question puis demander une reformulation adaptée au niveau.','L’interface conversationnelle ne renseigne pas à elle seule sur le système sous-jacent.','Attribuer une intention humaine au chatbot peut faire oublier ses limites.','Une conversation naturelle reste une interaction avec un système technique.']
];
for(const [id,title,desc,example,limit,risk,takeaway]of rows)if(!R.some(r=>r.id==='glossaire-'+id))R.push({...base,id:'glossaire-'+id,slug:'glossaire-'+id,type:'concept',title,desc,example,limit,risk,takeaway,category:'Comprendre l’IA',difficulty:'Débutant',objective:'Comprendre'});
const specific={
'intelligence-artificielle':['L’IA recouvre plusieurs familles de méthodes et ne possède pas une compétence universelle.','Confondre performance sur une tâche et compréhension humaine.','Évaluer le système sur le besoin précis.'],
'ia-generative':['La sortie est une proposition, pas une source documentaire.','Diffuser un texte plausible mais faux.','Générer puis vérifier sont deux étapes distinctes.'],
'prompt':['Une consigne ne donne pas accès à une information absente ou à une compétence inexistante.','Introduire des données identifiantes dans le contexte.','Préciser tâche, public, format et contrôle.'],
'hallucination':['On ne peut pas repérer toutes les erreurs au style du texte.','Croire une citation ou une référence inventée.','Vérifier les affirmations à leur source.'],
'llm':['La prédiction de tokens ne garantit pas un raisonnement correct.','Surinterpréter une réponse convaincante sur un sujet mal maîtrisé.','Tester les faits et les étapes indépendamment.'],
'token':['Un token ne correspond pas toujours à un mot ; le découpage dépend du modèle et de la langue.','Comparer des limites sans tenir compte de la tokenisation.','Les limites techniques portent souvent sur des tokens.'],
'fenetre-de-contexte':['Le contenu accessible au modèle est limité ; une longue conversation peut être tronquée ou résumée.','Supposer qu’un document ancien reste pris en compte.','Rappeler les informations utiles et vérifier ce qui est utilisé.'],
'multimodal':['Les performances varient selon le type de contenu et sa qualité.','Une image mal lue peut produire une réponse erronée.','Faire expliciter ce qui a été perçu avant d’en tirer une conclusion.'],
'rag':['Les passages récupérés peuvent être incomplets ou mal interprétés.','Prendre une citation réelle pour une preuve suffisante.','Ouvrir le passage cité et vérifier le lien avec la réponse.'],
'biais-algorithmique':['Le biais dépend des données, des objectifs et du contexte d’usage.','Reproduire des stéréotypes ou désavantager un groupe.','Examiner plusieurs profils fictifs et les erreurs associées.'],
'deepfake':['L’authenticité ne se déduit pas seulement d’artefacts visuels ou sonores.','Confondre imitation et preuve d’un propos réel.','Recouper par un canal indépendant connu.'],
'fine-tuning':['L’ajustement sur des exemples ne remplace pas la mise à jour documentaire ni tous les contrôles.','Suradapter le modèle à un corpus restreint.','Séparer entraînement et évaluation indépendante.'],
'agent':['Une chaîne d’actions peut cumuler les erreurs de ses étapes.','Autoriser des actions ou accès trop larges.','Délimiter les outils, les permissions et les conditions d’arrêt.'],
'entrainement':['Les données vues ne démontrent pas une généralisation à des situations nouvelles.','Réutiliser des données sans examiner droits et finalité.','Séparer données d’apprentissage et données de test.'],
'inference':['La réponse dépend du contexte et de la configuration du moment.','Considérer une réussite isolée comme une fiabilité constante.','Répéter des cas variés et documenter la configuration.'],
'raisonnement-genere':['Une explication affichée peut être plausible sans refléter un processus correct.','Confondre récit des étapes et preuve mathématique.','Vérifier chaque relation logique ou calcul.'],
'recherche-web':['Un lien récent ne garantit pas la qualité de la source.','Confondre résultat de recherche et fait établi.','Examiner auteur, date, passage et contexte.'],
'donnee-personnelle':['Plusieurs détails apparemment banals peuvent identifier une personne ensemble.','Réidentifier un élève malgré le retrait du nom.','Utiliser un exemple fictif dès que possible.'],
'pseudonymisation':['Le code reste personnel si un lien permet de retrouver l’identité.','Qualifier à tort les données d’anonymes.','Protéger aussi la correspondance et le contexte.'],
'anonymisation':['Supprimer les noms n’est qu’une étape et ne suffit pas toujours.','Sous-estimer le recoupement avec d’autres informations.','Examiner la possibilité de réidentification.'],
'droit-d-auteur':['L’accès à une œuvre n’emporte pas automatiquement tous les droits d’usage.','Importer ou publier sans autorisation adaptée.','Retrouver la licence et conserver la référence.'],
'modele-ouvert':['Ouverture des poids, du code et des données sont des dimensions distinctes.','Supposer qu’ouvert signifie libre de toute condition.','Lire la licence exacte et le périmètre ouvert.'],
'modele-proprietaire':['Les conditions et fonctions restent sous le contrôle du fournisseur.','Dépendre d’un service sans alternative de conservation.','Examiner export, conditions et possibilité de changer d’outil.'],
'tracabilite':['Une trace décrit le processus sans prouver à elle seule l’exactitude.','Accumuler des références sans les lire.','Relier chaque affirmation à une preuve consultée.'],
'evaluation-formative':['Un diagnostic ponctuel ne décrit pas toute une compétence.','Transformer automatiquement chaque essai en note définitive.','Utiliser l’information pour proposer le prochain apprentissage.']};
for(const r of R){const x=specific[r.id.replace('glossaire-','')];if(r.type==='concept'&&x)[r.limit,r.risk,r.takeaway]=x;}
};
