// Contenus originaux SCOLAR·IA. Les sources décrivent les repères, pas une homologation.
const date='2026-09-15';
const sources={unesco:'https://www.unesco.org/en/articles/ai-competency-framework-teachers',cndp:'https://www.cndp.ma/transfert-de-donnees-a-letranger/',loi:'https://www.cndp.ma/wp-content/uploads/2023/01/CNDP-depliant-fr.pdf'};
const academy=[
['decouvrir','Découvrir l’IA','Débutant','Acquérir',25,'Expliquer pourquoi une réponse fluide peut être fausse.','/comprendre/','/verifier/','Rédiger une définition de l’IA générative et vérifier une affirmation dans un manuel.','Une IA cite un livre que vous ne retrouvez pas.',['Citer le livre malgré tout','Marquer la référence non vérifiée et chercher une preuve','Faire voter la classe sur sa crédibilité'],1,'Une référence plausible reste non vérifiée sans document consultable.'],
['premiers-usages','Premiers usages pédagogiques','Débutant','Acquérir',30,'Choisir une petite tâche dont on peut contrôler le résultat.','/enseigner/','/generateur/','Préparer deux reformulations d’une consigne et expliquer laquelle conserve l’objectif.','Quel premier essai facilite le contrôle ?',['Faire noter toute la classe','Confier la progression annuelle entière','Reformuler une consigne dont on maîtrise le sens'],2,'Une tâche limitée et connue permet de comparer le résultat à un critère explicite.'],
['prompting','Maîtriser le prompting','Intermédiaire','Approfondir',40,'Réviser un prompt à partir d’un défaut observable.','/prompts/','/lab/ameliorer-prompt/','Conserver deux versions d’un prompt, le défaut corrigé et le critère de réussite.','Un prompt produit une activité trop longue. Que préciser ?',['Le temps total et le temps par étape','Demander une réponse brillante','Ajouter des noms d’élèves'],0,'Une contrainte vérifiable aide à juger la faisabilité.'],
['preparer-cours','Préparer ses cours avec l’IA','Intermédiaire','Approfondir',45,'Construire une séance à partir d’un objectif du cours effectivement enseigné.','/scenarios/','/lab/activite/','Adapter une séance de collège marocain : prérequis, trois phases et un transfert individuel.','Quelle preuve indique le mieux un apprentissage ?',['Une belle présentation générée','Une variante résolue individuellement et expliquée','Un prompt long'],1,'Le transfert révèle la capacité de l’élève à utiliser la notion dans une autre situation.'],
['creer-ressources','Créer des ressources pédagogiques','Intermédiaire','Approfondir',40,'Produire un support lisible, accessible et vérifié.','/tutoriels/','/lab/quiz/','Concevoir un support de cinq questions, son corrigé séparé et sa version papier.','Avant de distribuer un quiz généré, vous devez :',['Vérifier réponses, distracteurs et ambiguïtés','Conserver toujours la première réponse','Retirer le corrigé pour éviter de vérifier'],0,'La validation du contenu et des consignes reste une tâche de l’enseignant.'],
['evaluation','IA et évaluation','Intermédiaire','Approfondir',45,'Évaluer le raisonnement et la démarche avec des critères observables.','/evaluation/','/lab/grille/','Produire une grille sur 20, une question orale et une déclaration des aides autorisées.','Un détecteur signale un texte comme généré.',['Attribuer zéro automatiquement','Publier le résultat devant la classe','Examiner des traces et organiser une explication contradictoire'],2,'Un score de détection ne constitue pas une preuve suffisante pour sanctionner.'],
['eleves','IA et élèves','Débutant','Acquérir',35,'Faire pratiquer la vérification sans imposer de compte élève.','/enseigner-ia/','/verifier/','Animer une activité papier : affirmation, source, preuve et incertitude.','Une classe dispose de peu de connexions.',['Préparer une sortie fictive imprimée à analyser','Imposer un abonnement','Demander les identifiants des parents'],0,'Un support commun permet de travailler la même compétence sans compte personnel.'],
['donnees','Droit, éthique et données','Intermédiaire','Approfondir',40,'Distinguer obligation juridique, recommandation et décision de l’établissement.','/ethique/','/donnees-maroc/','Remplacer une copie réelle par un exemple fictif puis documenter les questions à adresser au responsable du traitement.','Un fichier avec des noms remplacés par des codes est :',['Toujours anonyme','Encore potentiellement identifiable','Automatiquement libre de diffusion'],1,'D’autres détails et les correspondances peuvent permettre une réidentification.'],
['avance','IA avancée pour enseignants','Avancé','Créer',55,'Tester un assistant documenté sur des cas connus et des cas sans réponse.','/comprendre/','/lab/analyser/','Créer trois questions répondables à partir d’un corpus et deux sans réponse ; consigner citations et erreurs.','Une réponse RAG cite un document. Est-elle nécessairement exacte ?',['Oui, la citation suffit','Oui si le document est long','Non, vérifier que le passage soutient réellement la réponse'],2,'La récupération de documents ne garantit pas une interprétation fidèle.'],
['assistants','Créer ses propres assistants IA','Avancé','Créer',60,'Définir le périmètre, le corpus et les limites d’un assistant pédagogique.','/lab/ameliorer-prompt/','/donnees-maroc/','Rédiger une fiche assistant : utilisateurs, corpus autorisé, refus attendus, cinq tests et procédure de mise à jour.','Quel test est indispensable ?',['Demander une réponse hors corpus et vérifier l’aveu d’incertitude','Tester seulement la question la plus facile','Vérifier uniquement la mise en page'],0,'Tester les limites est nécessaire pour détecter une confiance injustifiée.']
].map(([id,title,difficulty,stage,minutes,objective,learn,practice,production,question,answers,correct,explanation])=>({id,title,difficulty,stage,minutes,objective,learn,practice,production,question,answers,correct,explanation,source:sources.unesco,verifiedAt:date}));
const micro=[
['premier-prompt','Écrire son premier bon prompt',3,'Écrire une demande vérifiable.','Remplacer « fais un bon cours » par un objectif, un niveau et un format.','Exemple : prépare trois exercices de proportionnalité pour la 2e année collège, avec un corrigé séparé et une vérification des unités.','Vérifier que chaque exercice travaille bien la proportionnalité.','/generateur/'],
['hallucination','Repérer une affirmation non vérifiée',3,'Séparer assurance et preuve.','Souligner une date, un nom et une citation dans une réponse fictive.','Une référence inventée peut sembler crédible. Retrouver un document réel puis le passage qui soutient l’affirmation.','Conserver le statut « non vérifié » si la preuve manque.','/lab/analyser/'],
['cours-quiz','Transformer un cours en quiz',5,'Faire porter les questions sur les objectifs du cours.','Choisir trois notions et une erreur fréquente dans un extrait de votre propre cours.','Demander une question par notion, un distracteur plausible et l’explication du corrigé.','Résoudre soi-même chaque question et éliminer les formulations ambiguës.','/lab/quiz/'],
['grille','Construire une grille lisible',5,'Rendre la réussite observable.','Choisir quatre critères distincts pour une production.','Pour un raisonnement : démarche, exactitude, justification et autonomie. Décrire un indicateur pour chaque niveau.','Vérifier le total des points et ne pas compter deux fois la même compétence.','/lab/grille/'],
['donnees','Protéger les données avant de copier',3,'Éviter de transmettre une situation identifiable.','Lister ce que contient une copie : nom, écriture, notes, détails personnels.','Inventer un court exemple pour le même besoin pédagogique ; enlever le nom seul ne suffit pas.','Faire examiner le traitement réel par le responsable compétent de l’établissement.','/donnees-maroc/'],
['image','Préparer une image pédagogique',5,'Définir une image qui aide à comprendre.','Décrire l’objectif, le schéma attendu et les éléments à exclure.','Pour un circuit électrique, préparer les symboles et connexions à faire contrôler ; prévoir une légende textuelle.','Vérifier les erreurs scientifiques, les droits et l’absence de personnes identifiables.','/bibliotheque/?q=illustration'],
['resume','Résumer sans perdre une nuance',5,'Préserver les idées et les réserves du texte.','Fournir un extrait autorisé et demander cinq idées avec les passages justificatifs.','Comparer le résumé à l’extrait phrase par phrase. Séparer ce qui est dit de ce qui est déduit.','Réintroduire les conditions et exceptions omises.','/lab/ameliorer-prompt/'],
['sources','Vérifier une réponse et ses sources',10,'Évaluer la relation entre preuve et affirmation.','Choisir deux affirmations et chercher leurs sources primaires.','Noter auteur, date, passage précis, portée et limite de chaque source.','Une source réelle mais hors sujet ne valide pas l’affirmation.','/lab/analyser/'],
['exercice','Améliorer un exercice avec des aides',10,'Conserver le même objectif à plusieurs niveaux.','Définir un obstacle et deux aides : indice puis exemple partiel.','Prévoir ensuite une question commune sans aide pour tous.','Adapter le soutien, pas seulement la longueur ou le vocabulaire.','/lab/adapter/']
].map(([id,title,minutes,objective,action,example,check,link])=>({id,title,minutes,objective,action,example,check,link}));
const lab=[['ameliorer-prompt','Améliorateur de prompt','Transformer une demande en consigne structurée.'],['activite','Générateur d’activité','Composer un déroulement minuté à adapter à sa classe.'],['quiz','Préparer un quiz','Construire une demande de questions et de corrigé à partir d’un support.'],['grille','Grille d’évaluation','Créer une grille modifiable sur 20 points.'],['adapter','Trois niveaux d’aide','Préparer trois demandes avec le même objectif et des aides différentes.'],['analyser','Examiner une réponse IA','Construire une liste d’affirmations à vérifier et un journal de preuves.']].map(([id,title,desc])=>({id,title,desc}));
const toolReviews=[
{match:'Elicit',source:'https://elicit.com/pricing',note:'La page de l’éditeur propose une offre Basic gratuite et des offres payantes. La recherche, la synthèse et la consultation de sources sont décrites ; les quotas dépendent de l’offre. La clause de non-entraînement affichée pour Enterprise ne doit pas être généralisée aux autres offres.',cost:'Freemium',accountAccess:'Compte requis',privacyPolicy:'https://elicit.com/privacy',scope:['Offre gratuite et payante','Recherche documentaire','Exports variables selon l’offre']},
{match:'Perplexity',source:'https://www.perplexity.ai/help-center/en/articles/10352998-account-management-and-security',note:'Le centre d’aide permet certains usages sans connexion au compte. L’enregistrement des sessions et certaines fonctions demandent une connexion. Les quotas sont susceptibles de changer ; aucun quota chiffré n’est garanti ici.',cost:'Freemium',accountAccess:'Sans compte possible',scope:['Accès sans compte limité','Existence d’un compte gratuit et d’offres payantes']},
{match:'Canva pour l',source:'https://www.canva.com/education/',note:'Canva annonce une offre Education gratuite pour les enseignants et établissements éligibles du primaire et du secondaire, après vérification. Cela ne confirme ni l’éligibilité de chaque établissement marocain ni la conformité d’un traitement précis.',cost:'Gratuit sous conditions',accountAccess:'Compte requis',scope:['Offre Education soumise à éligibilité','Vérification du statut enseignant']},
{match:'DeepL Traducteur',source:'https://www.deepl.com/en/pro-data-security',note:'Cette page concerne les solutions professionnelles et présente des garanties de traitement des textes. Ces garanties ne sont pas étendues ici à la version gratuite. L’offre, le contrat, les transferts et les paramètres doivent être examinés pour le traitement envisagé.',scope:['Sécurité présentée pour les offres professionnelles']},
{match:'NotebookLM (Google)',source:'https://support.google.com/notebooklm/answer/17003757',note:'La documentation distingue les réponses ancrées dans les sources de NotebookLM et celles de Gemini qui peuvent mobiliser le Web. Elle explique aussi que les chats Gemini et les notebooks ne suivent pas nécessairement les mêmes règles de conservation.',scope:['Différence NotebookLM / Gemini','Conservation à examiner selon le produit']}
];
const uses=[['preparer','Préparer un cours'],['creer','Créer un support'],['evaluer','Évaluer'],['differencier','Différencier'],['verifier','Vérifier'],['proteger','Protéger les données'],['former','Former les élèves'],['rechercher','Rechercher des sources']];
const taxonomy={version:1,resourceTypes:['outil','prompt','tutoriel','scenario','guide','concept','source'],subjects:require('./scolaria.cjs').disciplines.map(d=>d[0]),levels:['1re année collège','2e année collège','3e année collège','Tronc commun','1re année baccalauréat','2e année baccalauréat'],useCases:uses.map(([id,label])=>({id,label})),languages:['fr','ar','zgh','en'],statuses:['active','review','archived'],privacyLevels:['unknown','caution','restricted','low'],accountAccess:['Sans compte possible','Compte requis','À vérifier','Sans objet'],studentAccess:['Activité encadrée sans compte IA','À vérifier'],toolKinds:['Service IA','Ressource complémentaire'],localeCoverage:{fr:'Complet pour les nouvelles pages',ar:'Accueil et navigation ; ressources françaises signalées',zgh:'Préparé, non traduit',en:'Introduction partielle existante'}};
function enrich(R){
 for(const m of micro)R.push({id:'micro-'+m.id,type:'guide',kind:'micro',title:m.title,desc:m.objective,objective:m.objective,category:'Micro-formations',discipline:'Toutes disciplines',level:'Collège et lycée',difficulty:'Débutant',language:'Français',cost:'Gratuit',media:'Texte',minutes:m.minutes,duration:m.minutes+' min',steps:[{t:'Essayer',d:m.action},{t:'Exemple',d:m.example},{t:'Contrôler',d:m.check}],example:m.example,tags:['microformation','formation'],audience:'Enseignant',reviewed:date,status:'contenu-editorial',sourceGrade:'Éditorial',related:[],link:'',tool:'Sans objet'});
 for(const r of R){
  const m=toolReviews.find(x=>r.type==='outil'&&r.title.startsWith(x.match));
  if(m){r.reviewEvidence={source:m.source,verifiedAt:date,scope:m.scope,note:m.note};r.checked=date;r.status='source-consultee';r.sourceGrade='C';r.verification='Revue documentaire ciblée, pas un test en classe. '+m.note;if(m.cost)r.cost=m.cost;if(m.accountAccess)r.account=m.accountAccess;r.accountAccess=m.accountAccess||'À vérifier';r.privacyPolicy=m.privacyPolicy||null;}
  r.slug=r.id;r.subjects=[r.discipline];r.levels=[r.level];r.languages=['Français','Arabe','Anglais'].includes(r.language)?[{Français:'fr',Arabe:'ar',Anglais:'en'}[r.language]]:[];
  r.provider=r.link?new URL(r.link).hostname.replace(/^www\./,''):null;
  r.toolKind=r.type==='outil'?(/GeoGebra|PhET|Scratch|Python Tutor|Mermaid|diagrams.net|OpenStax|Wikimedia|Zotero|Lire Couleur|Lecteur immersif/.test(r.title)?'Ressource complémentaire':'Service IA'):'Sans objet';
  r.accountAccess??=r.type==='outil'?'À vérifier':'Sans objet';r.studentAccess=r.kind==='activite'||r.type==='scenario'?'Activité encadrée sans compte IA':'À vérifier';
  r.privacyLevel='unknown';r.privacyLabel=r.type==='outil'?'À vérifier — aucune qualification de sécurité':'Modèle pédagogique — utiliser des données fictives';
  r.offline=r.connectivity||(/Papier|papier/.test(r.materials||'')?'Support imprimable':'À vérifier');r.ageMinimum=null;r.studentDataAllowed=null;
  r.verifiedAt=r.checked||null;r.editorialReviewedAt=r.reviewed||date;r.reviewAfter=r.verifiedAt?new Date(Date.parse(r.verifiedAt+'T00:00:00Z')+90*86400000).toISOString().slice(0,10):null;r.lifecycleStatus=r.verifiedAt?'active':r.type==='outil'||r.type==='source'?'review':'active';
  const hay=(r.title+' '+r.category+' '+r.objective+' '+(r.tags||[]).join(' ')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const rules={preparer:/cours|sequence|seance|prepar|objectif|progression/,creer:/creer|creation|support|image|video|audio|diagram|presentation/,evaluer:/evalu|quiz|qcm|bareme|grille|feedback|copie|dissertation/,differencier:/differenc|remedi|adapter|niveau|simplif/,verifier:/verif|biais|source|erreur|hallucin|preuve/,proteger:/donnee|droit|confiden|cndp|ethique/,former:/eleve|culture ia|activite|formation/,rechercher:/recherch|source|bibliog|scientifique/};
  r.useCases=Object.entries(rules).filter(([,re])=>re.test(hay)).map(([k])=>k);r.skills=r.useCases.map(k=>uses.find(x=>x[0]===k)[1]);r.translations??={};
  if(r.type==='prompt')r.variables=[...new Set([...r.text.matchAll(/\[[^\]\n]+\]/g)].map(m=>m[0]))];
 }
}
module.exports={date,sources,academy,micro,lab,taxonomy,toolReviews,enrich};
