const locales={
fr:{name:'Français',dir:'ltr',available:true,homeTitle:'L’intelligence artificielle au service des enseignants au Maroc',search:'Que souhaitez-vous faire avec l’IA ?'},
ar:{name:'العربية',dir:'rtl',available:true,homeTitle:'الذكاء الاصطناعي في خدمة المدرسات والمدرسين بالمغرب',search:'ماذا تريد أن تنجز بالذكاء الاصطناعي؟',intro:'موارد عملية للتخطيط للدروس، وإعداد الأنشطة، وتقويم التعلمات، وحماية المعطيات الشخصية. موجّه أساسًا إلى أساتذة التعليم الثانوي الإعدادي والتأهيلي بالمغرب.',note:'هذه الصفحة وواجهتها متاحتان بالعربية. الموارد المرتبطة موسومة باللغة الفرنسية عندما لا تتوفر ترجمتها بعد.',tasks:['إعداد درس','إنشاء نشاط','اختيار أداة','البحث عن طلب موجّه','التقويم','تكوين المتعلمين','فهم الذكاء الاصطناعي','حماية المعطيات','تكوين ذاتي','متابعة المستجدات']},
zgh:{name:'Tamaziɣt',dir:'ltr',available:false,homeTitle:null,search:null},
en:{name:'English',dir:'ltr',available:'partial',homeTitle:'AI for teachers in Morocco',search:'What would you like to do with AI?'}
};
const arLabels={'Votre quotidien':'عملك اليومي','Accueil':'الرئيسية','Découvrir l’IA':'فهم الذكاء الاصطناعي','Enseigner avec l’IA':'التدريس بالذكاء الاصطناعي','Par discipline':'حسب المادة','Promptothèque':'مكتبة الطلبات','Scénarios pédagogiques':'سيناريوهات تربوية','Évaluer autrement':'تجديد التقويم','Choisir & progresser':'الاختيار والتقدم','Annuaire des outils':'دليل الأدوات','Se former':'التكوين','SCOLARIA Academy':'أكاديمية سكولاريا','SCOLARIA Lab':'مختبر سكولاريا','Droit & éthique':'القانون والأخلاقيات','IA & éducation au Maroc':'الذكاء الاصطناعي والتعليم بالمغرب','Toutes les ressources':'جميع الموارد','Explorer toutes les rubriques':'استكشاف جميع الأقسام','Un portail indépendant':'بوابة مستقلة','Pour les enseignants du secondaire au Maroc.':'لأساتذة التعليم الثانوي بالمغرب.','Notre démarche →':'منهجنا ←','Mon espace':'فضائي','Favoris':'المفضلة','Langue du portail':'لغة البوابة','Aller au contenu':'الانتقال إلى المحتوى','Ouvrir la navigation':'فتح قائمة التصفح','Navigation principale':'التصفح الرئيسي','Fil d’Ariane':'مسار التصفح','Enseigner · Créer · Évaluer':'التدريس · الإبداع · التقويم','L’intelligence artificielle au service de l’éducation au Maroc.':'الذكاء الاصطناعي في خدمة التعليم بالمغرب.','Nos 10 principes':'مبادئنا العشرة','Méthode & sources':'المنهج والمصادر','Contribuer':'المساهمة','Confidentialité':'الخصوصية','Téléchargements':'التحميلات','SCOLAR·IA, livre ouvert et symbole du Maroc':'سكولاريا، كتاب مفتوح ورمز المغرب'};
function arabicShell(html){for(const [fr,ar] of Object.entries(arLabels).sort((a,b)=>b[0].length-a[0].length))html=html.split(fr).join(ar);return html.replace('<html lang="fr">','<html lang="ar" dir="rtl">').replaceAll('SCOLAR·IA · Pratique enseignante','سكولاريا · الممارسة التربوية').replaceAll('Ressources pratiques et documentées pour les enseignants du collège et du lycée au Maroc.','موارد عملية موثقة لأساتذة التعليم الثانوي بالمغرب.');}
module.exports={locales,arabicShell};
