const date='2026-09-15';
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const sources={talis:'https://www.oecd.org/en/publications/results-from-talis-2024-country-notes_e127f9e2-en/morocco_ee9859e2-en.html',cndp:'https://www.cndp.ma/conditions/',loi:'https://www.cndp.ma/images/lois/Loi-09-08-Fr.pdf',formalites:'https://www.cndp.ma/formalites/',unesco:'https://www.unesco.org/en/articles/ai-competency-framework-teachers',students:'https://unesdoc.unesco.org/ark:/48223/pf0000391105',experience:'https://experience-ai.org/uk/ai-literacy',ai4k12:'https://ai4k12.org/',day:'https://dayofai.org/',men:'https://www.men.gov.ma/fr/d%C3%A9veloppement-des-ressources-num%C3%A9riques',koun:'https://www.cndp.ma/communique-de-presse-la-cndp-lance-la-plateform0e-koun3labal-a-vocation-africaine-dediee-a-la-protection-de-la-vie-privee-et-du-traitement-des-donnees-a-caractere-personnel-des-enfant/'};
const disciplines=[
['Mathématiques','Comparer deux raisonnements de proportionnalité','Un résultat numérique juste ne prouve pas la validité du raisonnement.','une-solution-juste-pour-de-mauvaises-raisons'],
['Physique-chimie','Contrôler unités et hypothèses dans un bilan énergétique','Une formule plausible peut être utilisée hors de son domaine de validité.','audit-unites'],
['SVT','Distinguer observation, hypothèse et causalité','Une corrélation ne démontre pas un mécanisme biologique.','correlation-svt'],
['Français','Réviser un texte sans effacer la voix de son auteur','Une reformulation peut modifier le sens et uniformiser les productions.','atelier-voix'],
['Arabe','Comparer des reformulations en arabe standard','Contrôler le registre, la vocalisation et les références littéraires avec une source.','arabe-registre'],
['Anglais','Préparer un dialogue avec des objectifs linguistiques','Le niveau annoncé par un outil ne garantit pas le niveau réel du texte.','dialogue-anglais'],
['Histoire-géographie','Vérifier une chronologie et ses sources','Une citation ou une carte générée ne constitue pas une archive.','chronologie-sources'],
['Philosophie','Examiner un argument et son contre-exemple','Ne pas attribuer une formulation inventée à un philosophe.','contre-exemple'],
['Informatique','Tester un programme avant de le corriger','Un code exécutable peut rester incorrect ou dangereux.','tests-programme'],
['Technologie','Justifier une solution face à un cahier des charges','Les dimensions et contraintes de sécurité demandent un contrôle réel.','cahier-charges'],
['Économie','Interpréter un tableau de données fictives','Ne pas présenter une simulation comme une statistique officielle.','budget-fictif']
];
const scenarioSeeds=[
['audit-unites','Le calcul semble juste : et les unités ?','Physique-chimie','Tronc commun',50,'Vérifier une relation entre énergie, puissance et durée.','Puissance en watts, durée en heures et énergie en joules.','Une réponse fictive utilise E = P × t pour P = 100 W et t = 2 h, puis annonce 200 J.','Repérer la conversion manquante et démontrer que 720 000 J correspondent à 200 Wh.','Une correction commentée avec les unités à chaque étape.'],
['correlation-svt','Deux courbes, une causalité ?','SVT','1re année baccalauréat',55,'Distinguer corrélation et causalité.','Lecture de graphiques et variables.','Préparer deux séries fictives qui évoluent ensemble, sans relation causale établie.','Chercher une variable cachée et proposer un protocole permettant de tester une hypothèse.','Un schéma de protocole avec variables contrôlées.'],
['atelier-voix','Réviser un texte, garder sa voix','Français','3e année collège',55,'Justifier des choix de réécriture.','Paragraphe argumentatif et connecteurs.','Écrire un paragraphe fictif de 100 mots et préparer une réécriture trop soutenue.','Annoter cinq changements : utiles, inutiles ou porteurs d’un autre sens ; proposer sa propre version.','Deux versions annotées et une justification de 80 mots.'],
['arabe-registre','Quel registre pour quel lecteur ?','Arabe','Tronc commun',45,'Adapter un texte au public sans modifier les faits.','Arabe standard et registres de communication.','Préparer deux versions courtes en arabe d’une invitation fictive à un club scientifique.','Comparer les expressions, corriger les ambiguïtés et justifier le registre choisi.','Une invitation validée et un tableau de choix lexicaux.'],
['dialogue-anglais','Un dialogue qui fait vraiment parler','Anglais','2e année collège',45,'Poser une question et demander une clarification en anglais.','Interrogatives au présent.','Écrire une situation fictive : demander son chemin dans une école.','En binôme, jouer le dialogue, puis changer une contrainte sans lire le modèle.','Un dialogue de huit répliques et une reprise orale autonome.'],
['chronologie-sources','Une date, deux documents','Histoire-géographie','3e année collège',55,'Relier une affirmation historique à une source vérifiable.','Frise chronologique.','Choisir trois événements du chapitre dans le manuel autorisé ; produire une frise fictive avec une date déplacée.','Confronter chaque date aux pages du manuel et expliquer la correction.','Une frise sourcée avec auteur, titre et page.'],
['contre-exemple','Un argument résiste-t-il à un contre-exemple ?','Philosophie','2e année baccalauréat',55,'Distinguer thèse, prémisse et conclusion.','Construction d’un argument.','Présenter l’argument original : toute décision rapide est bonne parce qu’elle évite l’hésitation.','Construire un contre-exemple, expliciter la prémisse discutable et reformuler une thèse plus précise.','Une carte argumentative sans attribution fictive à un auteur.'],
['tests-programme','Trois tests avant toute correction','Informatique','Tronc commun',50,'Concevoir des cas de test indépendants du code.','Variables, conditions et division.','Proposer une fonction de moyenne qui divise toujours par trois, quelle que soit la liste.','Tester trois nombres, deux nombres et une liste vide ; définir le comportement attendu avant la correction.','Un tableau entrée / résultat attendu / résultat obtenu et le code corrigé.'],
['cahier-charges','Le meilleur objet pour quelles contraintes ?','Technologie','3e année collège',55,'Arbitrer une proposition technique avec un cahier des charges.','Mesure, matériaux et fonction d’usage.','Cahier fictif : support de livre, carton récupéré, charge de 500 g, largeur de 20 cm.','Comparer deux solutions dessinées ; construire un prototype papier et justifier les limites du test.','Une matrice contraintes / preuve / modification.'],
['budget-fictif','Un budget équilibré ne dit pas tout','Économie','1re année baccalauréat',55,'Contrôler un budget et expliciter les hypothèses.','Pourcentages et tableaux.','Budget fictif de club : recettes 1 200 MAD ; dépenses 450, 350 et 500 MAD.','Vérifier le déficit, proposer deux arbitrages et discuter ce que le budget ne mesure pas.','Un budget corrigé et une note d’arbitrage.'],
['carte-eau','Une carte de l’eau, des données à documenter','Histoire-géographie','Tronc commun',60,'Distinguer carte illustrative et donnée géographique.','Légende, échelle et unité.','Dessiner trois zones fictives et une légende présentant des quantités sans unité.','Réparer la légende, préciser période et source ; écrire pourquoi cette carte ne décrit pas le Maroc réel.','Une carte explicitement fictive et sa notice méthodologique.'],
['probabilite-modele','Prédire la suite sans comprendre le monde','Mathématiques','1re année baccalauréat',50,'Calculer une fréquence et discuter une prédiction.','Fréquences et probabilités élémentaires.','Corpus original : 6 phrases commencent par « Le soleil », 3 par « Le vent », 1 par « Le train ».','Calculer les fréquences, prédire un mot, puis tester la phrase « Le train arrive ».','Un tableau de fréquences et une limite du modèle simplifié.'],
['texte-accessible','Une consigne accessible, le même objectif','Français','1re année collège',45,'Alléger une consigne sans réduire la tâche cognitive.','Verbes de consigne.','Préparer une consigne originale à trois étapes, avec mots rares et phrase longue.','Séparer les étapes, définir deux termes et vérifier que la justification reste demandée.','Une version accessible avec les invariants de la tâche.'],
['debat-energie','Faut-il une IA pour cette tâche ?','Sciences de l’ingénieur','2e année baccalauréat',55,'Arbitrer utilité, ressources et simplicité d’une solution.','Comparaison multicritère.','Trois tâches : additionner un budget, traduire un brouillon, simuler une structure.','Choisir calculatrice, expertise humaine ou IA et défendre le choix avec limites ; ne pas inventer de consommation chiffrée.','Une recommandation contextualisée avec option sans IA.']
];
const activities=[
['Trier des objets : règle ou apprentissage ?','Collège',30,'Perception','Dessiner douze objets avec forme et couleur. Un groupe écrit une règle explicite ; un autre déduit une règle à partir de six exemples étiquetés. Tester les six autres et comparer les erreurs.','Un tableau règle / exemple / erreur.','L’apprentissage dépend des exemples ; ce jeu ne reproduit pas toute une IA.'],
['Un jeu de données représentatif','Collège',40,'Données','Créer 12 cartes de feuilles : 9 rondes et 3 longues. En garder quatre pour le test. Construire un classifieur papier puis ajouter des feuilles longues et observer ce qui change.','Une matrice prévision / étiquette réelle.','Le jeu est fictif ; ne pas classer les personnes.'],
['Entraîner sans regarder le contrôle','Lycée',40,'Machine learning','Préparer 15 cartes nombres : 10 exemples et 5 tests cachés. Faire découvrir la règle « multiple de trois ». Comparer un groupe qui voit les tests et un qui ne les voit pas.','Une explication de la fuite de données et du test indépendant.','Réussir sur des exemples mémorisés ne mesure pas la généralisation.'],
['Le prochain mot','Collège',30,'LLM','Créer dix débuts de phrases et compter les mots qui suivent. Tirer un mot selon les fréquences ; essayer ensuite un début absent du corpus.','Trois phrases produites et deux limites.','Un jeu de fréquences illustre une intuition, pas le fonctionnement complet d’un LLM.'],
['Une source qui n’existe pas','Collège',35,'Hallucinations','Fournir une référence explicitement fictive « Revue des robots scolaires, volume 999 ». Définir les traces qui permettraient de vérifier une référence puis travailler sur une vraie source du manuel.','Une fiche auteur / titre / publication / accès / conclusion.','Une absence dans un moteur ne suffit pas seule à prouver l’inexistence.'],
['Le biais dans les exemples','Lycée',40,'Biais','Décrire des métiers fictifs en attribuant tous les rôles techniques au même personnage. Faire compter les rôles, rééquilibrer les exemples puis discuter les stéréotypes qui subsistent.','Une grille des représentations et une version corrigée.','Corriger un corpus ne garantit pas l’absence de biais.'],
['Le portrait des données personnelles','Collège',35,'Vie privée','Classer des cartes fictives : prénom seul, prénom et classe, voix, note, recette de cuisine. Expliquer les combinaisons qui rendent une personne identifiable.','Une affiche des informations à retirer avant un partage.','Le remplacement du nom peut laisser la personne reconnaissable.'],
['Pourquoi me recommande-t-on ceci ?','Collège',40,'Recommandations','Simuler trois profils fictifs de lecture et six livres. Classer les livres selon les lectures précédentes, puis imposer un choix de découverte.','Deux classements justifiés et une discussion sur la diversité.','Ne pas collecter l’historique réel des élèves.'],
['Une image convaincante n’est pas une preuve','Collège',35,'Images générées','Dessiner une image impossible mais cohérente. Séparer ce que l’image montre de ce que l’on sait de son origine ; établir les vérifications nécessaires avant publication.','Une légende qui signale l’illustration et son origine.','Les défauts visuels ne constituent pas un détecteur fiable.'],
['Le message audio imité','Lycée',40,'Deepfakes','Lire deux transcriptions fictives d’un appel urgent demandant une action. Imaginer une procédure de rappel par un canal connu et une preuve indépendante.','Un protocole de vérification à deux canaux.','Aucun enregistrement ni clonage de voix d’une personne réelle.'],
['Des neurones en papier','Lycée',45,'Réseaux neuronaux','Attribuer deux entrées 0/1 à des cartes, des poids 1 et 2, un seuil 2. Calculer quatre sorties puis modifier le seuil. Discuter ce que ce modèle élémentaire ne peut pas faire.','Une table entrées / somme / sortie.','Ne pas assimiler ce calcul simplifié au cerveau humain.'],
['Quel travail reste humain ?','Lycée',45,'IA et travail','Décomposer un métier fictif en six tâches. Classer assistance possible, décision humaine et responsabilité. Changer le contexte et réviser le classement.','Une carte des tâches avec responsabilités.','Une possibilité technique ne prouve ni remplacement ni suppression d’emploi.'],
['Une IA pour quel coût collectif ?','Lycée',40,'Environnement','Comparer trois moyens de faire une affiche : papier, logiciel et génération. Lister équipements, données et usages sans inventer de chiffres carbone.','Une décision argumentée et les informations manquantes.','L’impact dépend du modèle, de l’énergie, du matériel et du volume.'],
['Un débat démocratique avec des preuves','Lycée',50,'Société','Simuler un conseil de classe fictif qui veut automatiser le choix des livres. Attribuer des rôles contradictoires et exiger une source pour chaque affirmation factuelle.','Une décision motivée avec avis minoritaire.','Les personnes réelles et leurs opinions ne servent pas de données.'],
['Concevoir un assistant de bibliothèque','Lycée',55,'Conception','Créer cinq notices originales de livres fictifs, écrire une règle de recommandation et tester trois demandes dont une sans réponse dans le corpus.','Une fiche besoin / corpus / règle / tests / limites.','Un assistant doit savoir signaler ce qu’il ne sait pas.']
];
const evals=[
['Devoir maison avec étapes visibles','Collecter un plan, un brouillon annoté et une justification finale. Évaluer les choix plutôt que la seule fluidité du texte.','Un plan en classe puis une révision à la maison avec déclaration.'],
['Oral de justification','Demander à l’élève d’expliquer une décision et de traiter une variante inattendue. Annoncer ces critères avant le travail.','Deux minutes pour justifier une source puis répondre à un contre-exemple.'],
['Grille d’un écrit argumentatif','Séparer la pertinence de la thèse, les preuves, le raisonnement et la qualité linguistique. Adapter les poids au contrat annoncé.','Quatre critères sur quatre niveaux avec exemples observables.'],
['Évaluation formative à partir d’une erreur','Présenter une réponse fictive erronée, recueillir une correction et une explication ; ne pas confondre diagnostic et note définitive.','Repérer une conversion manquante et justifier l’unité correcte.'],
['Évaluer une recherche documentaire','Exiger une table affirmation / passage source / référence / limite. Une bibliographie seule ne démontre pas la lecture.','Vérifier trois affirmations d’un exposé.'],
['Projet collectif et responsabilité individuelle','Prévoir une trace commune et une explication individuelle courte. Distinguer production du groupe et compréhension de chacun.','Un membre explique un choix qu’il n’a pas rédigé.'],
['Contrôle individuel sans IA','Annoncer les ressources permises, prévoir un sujet aligné avec l’apprentissage et organiser des conditions équitables.','Une variante de problème réalisée en classe sans assistant.'],
['IA limitée à la reformulation','Autoriser une étape précise, interdire la production de l’argument et demander les changements acceptés ou refusés.','L’élève conserve sa première formulation et motive deux révisions.'],
['Évaluer la critique d’une réponse IA','Fournir la même sortie à toute la classe. Noter la vérification, les preuves et la correction, pas la maîtrise d’un compte payant.','Quatre erreurs dans un document fictif fourni par l’enseignant.'],
['Traiter un soupçon avec prudence','Un score de détection ne constitue pas une preuve suffisante. Revenir aux traces, écouter l’élève et appliquer la procédure de l’établissement.','Entretien fondé sur le travail et ses sources ; pas d’accusation automatisée.']
];
const legal=[
['Nom, classe et copie : que retirer ?','Un nom masqué ne suffit pas si le récit, la classe ou la combinaison de détails identifie encore l’élève. Pour une démonstration, écrire un exemple fictif.','loi'],
['Photographies et voix des élèves','Le son et l’image peuvent concerner une personne identifiable. Préférer des illustrations et voix fictives ; faire examiner tout projet réel par l’établissement.','loi'],
['Notes et commentaires scolaires','Éviter d’envoyer un tableau de notes nominatif à un service grand public. Faire une simulation pédagogique avec des données créées pour cet usage.','loi'],
['Données de santé et besoins particuliers','Ne pas saisir un diagnostic pour obtenir une adaptation. Décrire uniquement le besoin pédagogique général, sans histoire personnelle.','loi'],
['Le consentement suffit-il ?','Ne pas assimiler consentement et conformité globale. Il faut aussi examiner la finalité, les informations données, la sécurité et les formalités applicables.','formalites'],
['Qui décide dans l’établissement ?','Faire clarifier le responsable du traitement, la finalité et les prestataires avant un déploiement. Un enseignant ne doit pas présumer pouvoir engager l’établissement.','cndp'],
['Données traitées à l’étranger','Identifier les pays et les destinataires, puis faire examiner les conditions et formalités de transfert. Une politique européenne ne règle pas à elle seule le cas marocain.','formalites'],
['Durée de conservation','Définir combien de temps le contenu est nécessaire, qui y accède et comment sa suppression sera vérifiée. Examiner aussi copies et sauvegardes du prestataire.','cndp'],
['Sécuriser un usage partagé','Employer des accès individuels autorisés, limiter les droits et éviter le partage d’identifiants. Documenter les incidents et le contact interne compétent.','cndp'],
['Informer élèves et familles','Expliquer la tâche, les données éventuelles, le rôle de l’outil et l’alternative. Utiliser une information compréhensible plutôt qu’une formule générale « usage du numérique ».','cndp'],
['Un pseudonyme est-il anonyme ?','Un code peut rester relié à un élève par une table ou par le contexte. Distinguer pseudonymisation et impossibilité raisonnable de réidentification.','loi'],
['Réutiliser un manuel scolaire','Avant l’import, vérifier la licence et les autorisations couvrant la reproduction et l’envoi au prestataire. À défaut, utiliser un texte original ou autorisé.','auteur'],
['Réutiliser une image trouvée en ligne','Retrouver l’auteur et la licence. Une image accessible par recherche n’est pas nécessairement réutilisable ; conserver la référence et les conditions.','auteur'],
['Publier une image générée','Contrôler droits antérieurs, personnes représentées et conditions du service. Signaler l’origine générée lorsque cela évite de tromper le lecteur.','auteur'],
['Citer une IA et ses sources','Déclarer outil, date, tâche et transformations. Citer séparément les documents effectivement lus ; ne pas transformer une référence proposée par l’IA en source vérifiée.','auteur']
];
function enrich(R){const base={discipline:'Toutes disciplines',level:'Collège et lycée',difficulty:'Intermédiaire',language:'Français',cost:'Gratuit',media:'Texte',reviewed:date,status:'contenu-editorial',tags:[],related:[],translations:{}};const add=r=>{if(!R.some(x=>x.id===r.id))R.push({...base,...r,slug:r.id})};require('./concepts.cjs')(R,base);add({id:'ocde-talis-2024-maroc',type:'source',title:'OCDE — TALIS 2024, note Maroc',desc:'Source primaire de l’enquête déclarative auprès des enseignants du premier cycle du secondaire. Distinguer la population totale et les non-utilisateurs de l’IA.',category:'Sources & veille',link:sources.talis,checked:date,status:'source-consultee',verification:'Note institutionnelle consultée ; enquête déclarative, pas une mesure directe d’efficacité.'});const oldTalis=R.find(r=>r.title.includes('LesEco.ma')&&r.title.includes('TALIS'));if(oldTalis)oldTalis.desc='Article de presse conservé comme source secondaire. Pour les données et leur population, consulter la note OCDE et la rubrique Maroc.';
for(const [id,title,discipline,level,minutes,desc,prerequisites,preparation,task,expected] of scenarioSeeds)add({id,title,type:'scenario',discipline,level,minutes,duration:minutes+' min',desc,category:'Enseigner & vérifier',objective:desc,context:'Proposition à adapter au programme effectivement étudié ; groupes de trois, puis production individuelle.',prerequisites,preparation,expected,materials:'Papier et tableau. Sortie IA éventuellement préparée par l’enseignant ; aucun compte élève requis. Support utilisable sans connexion.',steps:[{t:'Observer · 10 min',d:preparation},{t:'Enquêter · '+(minutes-25)+' min',d:task},{t:'Mettre en commun · 10 min',d:'Comparer deux solutions, demander une preuve et corriger les interprétations.'},{t:'Transférer · 5 min',d:'Chaque élève répond seul à une variante et explique une vérification utile.'}],roles:{teacher:'Prépare le support, contrôle son exactitude et anime la confrontation.',ai:'Propose éventuellement un brouillon avant la classe ; ne décide ni de la validité finale ni de la note.',students:'Testent, argumentent, corrigent et gardent une trace.'},evaluation:'Évaluer exactitude, justification et transfert individuel ; '+expected,variants:'Aide : tableau partiellement rempli et vocabulaire explicité. Approfondissement : inventer un nouveau contre-exemple. Sans IA : utiliser le support fictif décrit.',pitfall:'Vérifier les faits et utiliser uniquement des données fictives ; ne pas imposer un outil à domicile.',prompt:'Agis comme concepteur pédagogique. Prépare un support fictif pour : '+desc+' Contexte : '+level+' au Maroc. Tâche : '+task+' Fournis un corrigé séparé, les hypothèses et les éléments à vérifier.',connectivity:'Hors ligne possible',device:'Papier / smartphone enseignant',audience:'Enseignant',tool:'Assistant au choix'});
for(const [i,[title,level,minutes,category,task,expected,risk]]of activities.entries())add({id:'activite-'+slug(title),title,type:'guide',kind:'activite',level,minutes,duration:minutes+' min',category:'Culture IA élèves',objective:category,desc:'Une activité originale pour comprendre '+category.toLowerCase()+' par la manipulation et la discussion.',steps:[{t:'Préparer',d:'Papier, feutres et tableau ; aucun compte ni donnée réelle. Groupes de trois.'},{t:'Expérimenter',d:task},{t:'Expliciter',d:'Faire distinguer ce que la simulation montre de ce qu’elle ne permet pas de conclure.'},{t:'Vérifier les acquis',d:expected},{t:'Adapter',d:'Soutien : moins de cartes et lexique bilingue. Extension : produire un contre-exemple et expliquer son effet.'}],expected,pitfall:risk,sourceLinks:[sources.students,i%2?sources.ai4k12:sources.experience],connectivity:'Hors ligne',device:'Papier',audience:'Élève accompagné'});
for(const [title,desc,example]of evals)add({id:'eval-'+slug(title),type:'guide',title,desc,category:'Évaluation',objective:'Évaluer',kind:'evaluation',example,steps:[{t:'Fixer le contrat',d:desc},{t:'Mettre en œuvre',d:example},{t:'Conserver les preuves',d:'Recueillir une trace initiale, les décisions prises et une explication individuelle.'},{t:'Retour à l’élève',d:'Nommer un acquis observable et un prochain geste de progression, sans jugement sur la personne.'}]});
for(const [title,desc,key] of legal)add({id:'droit-'+slug(title),type:'guide',title,desc,category:'Droit & données',kind:'droit',objective:'Encadrer',sourceLinks:[key==='auteur'?'https://www.wipo.int/wipolex/en/text/567222':sources[key]],steps:[{t:'Repère pratique',d:desc},{t:'Avant un usage réel',d:'Documenter la finalité et les conditions ; consulter le responsable désigné dans l’établissement.'},{t:'Alternative immédiate',d:'Utiliser un exemple original fictif sans information sur une personne réelle.'}]});
for(const [i,d]of disciplines.entries()){const [discipline,use,risk]=d;add({id:'prompt-atelier-'+slug(discipline),type:'prompt',title:'Atelier '+discipline+' : '+use.toLowerCase(),discipline,category:'Conception de séance',objective:use,duration:'15 à 25 min de préparation',audience:'Enseignant',tool:'Assistant conversationnel',desc:use+'. Le modèle impose une trace de vérification et une variante sans IA.',text:`RÔLE : tu m’aides à concevoir une activité de ${discipline}.\nCONTEXTE : [niveau], [effectif] élèves au Maroc ; sujet [sujet].\nOBJECTIF : ${use}. Compétence ciblée : [compétence].\nCONTRAINTES : [durée], [matériel], corpus autorisé [source]. Ne traite aucune donnée personnelle.\nTÂCHE : propose une activité active avec consigne, étapes minutées et deux aides graduées.\nFORMAT : tableau étape / action élève / preuve attendue / rôle enseignant ; corrigé séparé.\nQUALITÉ : distingue hypothèse et fait. ${risk}\nVÉRIFICATION : liste les points que je dois contrôler ; prévois une variante sans compte et un transfert individuel.`,example:'Un groupe de 30 élèves, 45 minutes, documents préparés par l’enseignant, restitution sur papier.',expected:'Un déroulement, une trace élève, un corrigé et une liste de vérifications.',advice:risk,advanced:'Ajouter une variante qui contredit une hypothèse de départ et demander à l’élève d’expliquer ce qui change.'});}
add({id:'prompt-message-familles',type:'prompt',title:'Expliquer une activité IA aux familles',category:'Communication',objective:'Communiquer',audience:'Enseignant',tool:'Assistant conversationnel',desc:'Préparer une information claire sur les objectifs, les données et l’alternative sans compte.',text:'Rédige une note de 150 mots destinée aux familles. Activité : [activité]. Niveau : [niveau]. Objectif : [objectif]. Aucun compte élève ni donnée personnelle ne sera nécessaire dans ce scénario. Décris le rôle de l’enseignant, la vérification et l’alternative [alternative]. N’invente aucune autorisation, promesse ni politique de l’établissement. Termine par [contact institutionnel].',example:'Activité papier de critique d’une réponse fictive en classe.',expected:'Un brouillon de note à valider par l’établissement.',advice:'Vérifier que les engagements décrits correspondent exactement au dispositif retenu.'});
const tools=[['Curipod','https://curipod.com/','Séquences interactives pilotées par l’enseignant, notamment autour de l’écriture.','https://curipod.com/privacy-policy'],['Adobe Express','https://helpx.adobe.com/express/web/adobe-express-for-education/for-educators/education-overview.html','Créer des supports visuels et des productions multimédias dans un cadre éducatif à vérifier.','https://helpx.adobe.com/business/education/generative-ai-and-adobe-express/adobe-firefly-for-k12-ssp.html'],['Napkin','https://www.napkin.ai/ai-transparency/','Transformer un texte en représentations visuelles à relire et adapter.','https://help.napkin.ai/en/articles/15950953-privacy-data']];
for(const [title,link,desc,policy]of tools)add({id:slug(title),type:'outil',title,link,desc,category:'Création de supports',example:'L’enseignant prépare un support avec un texte original fictif, puis contrôle les informations avant projection.',benefits:['Brouillon visuel ou pédagogique à adapter à une tâche explicite.'],limits:['Efficacité pédagogique non mesurée par SCOLAR·IA.','Conditions, quotas et disponibilité au Maroc à confirmer pour le compte retenu.'],privacy:title==='Napkin'?'Documentation consultée contradictoire sur l’entraînement : le centre d’aide évoque un usage anonymisé avec opposition, tandis que les conditions distinguent le contenu visuel. Clarifier l’offre et les réglages avant tout contenu sensible.':'Lire la politique correspondant à l’offre et vérifier le cadre marocain avant toute donnée réelle.',policy,account:'Information non documentée',cost:'À vérifier',status:'source-consultee',checked:date,verification:'Présentation officielle consultée ; fonctionnement en compte non testé.',sourceLinks:[link,policy]});
for(const r of R){r.audience??=r.type==='guide'&&r.kind==='activite'?'Élève accompagné':'Enseignant';r.tool??=r.type==='prompt'?'Assistant conversationnel':'Sans objet';r.sourceGrade=r.type==='source'?(/cndp|men.gov|unesco|oecd|wipo|um6p/i.test(r.link)?'A':/leseco/i.test(r.link)?'D':'B'):r.type==='outil'?(r.checked?'C':'E'):'Éditorial';if(r.type==='outil'){r.documentation={public:'Préparation par l’enseignant ; usage élève à examiner séparément',age:'Information non documentée',studentAccount:'Information non documentée',hosting:'Information non documentée',mobile:'Information non documentée',import:'Information non documentée',citations:'Information non documentée',images:'Information non documentée',french:'Information non documentée',arabic:'Information non documentée',english:'Information non documentée'};r.recommendation='Essai prudent par l’enseignant sur des contenus fictifs ; usage élève sous conditions à vérifier.';}if(r.type==='prompt'){r.duration??='10 à 20 min de préparation indicative';r.advanced??='Demander deux approches, préciser leurs hypothèses, puis produire un contre-exemple et une solution de secours sans IA.';r.risk??='Un prompt détaillé ne garantit ni exactitude, ni alignement au programme, ni confidentialité.';}if(r.type==='concept'){r.limit??='Cette notion décrit un mécanisme ou un usage ; elle ne garantit pas la qualité d’un résultat particulier.';r.risk??='Éviter de déduire une capacité générale d’un seul exemple réussi.';r.takeaway??='Définir le besoin, tester sur un cas connu et garder une vérification humaine.';}}
}
module.exports={enrich,disciplines,activities,evals,legal,sources,slug,date};
